// Code generated by gen_modules.py. DO NOT EDIT.

package api

import (
	"context"

	"github.com/norbix-code/sdk-go/norbix/internal/transport"
)

// ChatModule groups the chat endpoints on the API.
type ChatModule struct{ t *transport.Transport }

// AskChat performs POST /{version}/chat/complete (scope: project).
func (m *ChatModule) AskChat(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/chat/complete",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
