// Code generated by gen_modules.py. DO NOT EDIT.

package api

import (
	"context"

	"github.com/norbix-code/sdk-go/norbix/internal/transport"
)

// DatabaseModule groups the database endpoints on the API.
type DatabaseModule struct{ t *transport.Transport }

// FindTerms performs GET /{version}/database/taxonomies/{taxonomyName}/terms (scope: project).
func (m *DatabaseModule) FindTerms(ctx context.Context, taxonomyName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"taxonomyName": taxonomyName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/taxonomies/{taxonomyName}/terms",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// FindTermsChildren performs GET /{version}/database/taxonomies/{taxonomyName}/terms/{parentId}/children (scope: project).
func (m *DatabaseModule) FindTermsChildren(ctx context.Context, taxonomyName string, parentId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"taxonomyName": taxonomyName,
		"parentId":     parentId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/taxonomies/{taxonomyName}/terms/{parentId}/children",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// FindTermTree performs GET /{version}/database/taxonomies/{taxonomyName}/terms/tree (scope: project).
func (m *DatabaseModule) FindTermTree(ctx context.Context, taxonomyName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"taxonomyName": taxonomyName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/taxonomies/{taxonomyName}/terms/tree",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// FindTaxonomyTree performs GET /{version}/database/taxonomies/tree (scope: project).
func (m *DatabaseModule) FindTaxonomyTree(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/taxonomies/tree",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchema performs GET /{version}/database/schemas/{id} (scope: project).
func (m *DatabaseModule) GetDatabaseSchema(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/schemas/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchemas performs GET /{version}/database/schemas (scope: project).
func (m *DatabaseModule) GetDatabaseSchemas(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/schemas",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// Aggregate performs POST /{version}/database/collections/{collectionName}/aggregate (scope: project).
func (m *DatabaseModule) Aggregate(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/aggregate",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ChangeResponsibility performs PUT /{version}/database/collections/{collectionName}/{id}/responsibility (scope: project).
func (m *DatabaseModule) ChangeResponsibility(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/{id}/responsibility",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// Count performs GET /{version}/database/collections/{collectionName}/count (scope: project).
func (m *DatabaseModule) Count(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/count",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteMany performs DELETE /{version}/database/collections/{collectionName}/many (scope: project).
func (m *DatabaseModule) DeleteMany(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/many",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteOne performs DELETE /{version}/database/collections/{collectionName}/{id} (scope: project).
func (m *DatabaseModule) DeleteOne(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/{id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// Distinct performs GET /{version}/database/collections/{collectionName}/distinct (scope: project).
func (m *DatabaseModule) Distinct(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/distinct",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ExecuteAggregate performs POST /{version}/database/collections/{collectionName}/aggregates/{aggregateId}/execute (scope: project).
func (m *DatabaseModule) ExecuteAggregate(ctx context.Context, collectionName string, aggregateId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"aggregateId":    aggregateId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/aggregates/{aggregateId}/execute",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// Find performs GET /{version}/database/collections/{collectionName} (scope: project).
func (m *DatabaseModule) Find(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// FindOne performs GET /{version}/database/collections/{collectionName}/{id} (scope: project).
func (m *DatabaseModule) FindOne(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// InsertMany performs POST /{version}/database/collections/{collectionName}/many (scope: project).
func (m *DatabaseModule) InsertMany(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/many",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// InsertOne performs POST /{version}/database/collections/{collectionName} (scope: project).
func (m *DatabaseModule) InsertOne(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ReplaceOne performs PUT /{version}/database/collections/{collectionName}/{id}/replace (scope: project).
func (m *DatabaseModule) ReplaceOne(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/{id}/replace",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateMany performs PUT /{version}/database/collections/{collectionName}/many (scope: project).
func (m *DatabaseModule) UpdateMany(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/many",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateOne performs PUT /{version}/database/collections/{collectionName}/{id} (scope: project).
func (m *DatabaseModule) UpdateOne(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/{id}",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
