// Code generated by gen_modules.py. DO NOT EDIT.

package api

import (
	"context"

	"github.com/norbix-code/sdk-go/v2/norbix/internal/transport"
)

// DatabaseModule groups the database endpoints on the API.
type DatabaseModule struct{ t *transport.Transport }

// FindTerms performs GET /{version}/database/taxonomies/{taxonomyName}/terms (scope: project).
//
// It lists the terms of a taxonomy.
//
// It needs database:read on database:term:<taxonomy id>. An unknown taxonomy name answers
// CM-ERRORS-TAXONOMIES-010; a name over 40 characters answers CM-ERRORS-TAXONOMIES-005.
//
// A "filter" with $where, $function or $accumulator is refused with CM-ERRORS-DATABASE-031.
func (m *DatabaseModule) FindTerms(ctx context.Context, taxonomyName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"taxonomyName": taxonomyName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/taxonomies/{taxonomyName}/terms",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// FindTermsChildren performs GET /{version}/database/taxonomies/{taxonomyName}/terms/{parentId}/children (scope: project).
//
// It lists the child terms of "parentId".
//
// It needs database:read on database:term:<taxonomy id>. An unknown taxonomy name answers
// CM-ERRORS-TAXONOMIES-010; a name over 40 characters answers CM-ERRORS-TAXONOMIES-005.
//
// A "filter" with $where, $function or $accumulator is refused with CM-ERRORS-DATABASE-031.
func (m *DatabaseModule) FindTermsChildren(ctx context.Context, taxonomyName string, parentId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"taxonomyName": taxonomyName,
		"parentId":     parentId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/taxonomies/{taxonomyName}/terms/{parentId}/children",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// FindTermTree performs GET /{version}/database/taxonomies/{taxonomyName}/terms/tree (scope: project).
//
// It returns the terms of a taxonomy as a tree ("rootTermId", "depth").
//
// It needs database:read on database:term:<taxonomy id>. An unknown taxonomy name answers
// CM-ERRORS-TAXONOMIES-010; a name over 40 characters answers CM-ERRORS-TAXONOMIES-005. More than 5000
// terms answers CM-ERRORS-TAXONOMIES-011; read a sub-tree instead (rootTermId, depth).
func (m *DatabaseModule) FindTermTree(ctx context.Context, taxonomyName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"taxonomyName": taxonomyName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/taxonomies/{taxonomyName}/terms/tree",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// FindTaxonomyTree performs GET /{version}/database/taxonomies/tree (scope: project).
//
// It returns every taxonomy as a tree ("includeTerms" adds the terms).
//
// With "includeTerms" the call fails when the term read fails. More than 5000 terms answers
// CM-ERRORS-TAXONOMIES-011; read a sub-tree instead (rootTermId, depth).
func (m *DatabaseModule) FindTaxonomyTree(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/taxonomies/tree",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchema performs GET /{version}/database/schemas/{id} (scope: project).
func (m *DatabaseModule) GetDatabaseSchema(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/schemas/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchemas performs GET /{version}/database/schemas (scope: project).
func (m *DatabaseModule) GetDatabaseSchemas(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/schemas",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// Aggregate performs POST /{version}/database/collections/{collectionName}/aggregate (scope: project).
func (m *DatabaseModule) Aggregate(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/aggregate",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ChangeResponsibility performs PUT /{version}/database/collections/{collectionName}/{id}/responsibility (scope: project).
//
// It moves one record to "newResponsibleUserId".
//
// A new owner who is not a user of the project in the request environment is refused with
// CM-ERRORS-MEMBERSHIP-USERS-012.
//
// Soft-deleted records are not matched: such a record is "not found".
func (m *DatabaseModule) ChangeResponsibility(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/{id}/responsibility",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// Count performs GET /{version}/database/collections/{collectionName}/count (scope: project).
func (m *DatabaseModule) Count(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/count",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteMany performs DELETE /{version}/database/collections/{collectionName}/many (scope: project).
//
// It deletes every record that matches "filter" (sent in the query string, with "allRecords").
//
// An empty filter ("{}") touches every record, so the gateway refuses it with CM-ERRORS-DATABASE-037
// unless "allRecords" is true.
//
// A caller with only own-record rights (createAsUser / updateOwn / deleteOwn) may call it; it then
// touches only that caller's records.
func (m *DatabaseModule) DeleteMany(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/many",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteOne performs DELETE /{version}/database/collections/{collectionName}/{id} (scope: project).
func (m *DatabaseModule) DeleteOne(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/{id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// Distinct performs GET /{version}/database/collections/{collectionName}/distinct (scope: project).
func (m *DatabaseModule) Distinct(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/distinct",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ExecuteAggregate performs POST /{version}/database/collections/{collectionName}/aggregates/{aggregateId}/execute (scope: project).
func (m *DatabaseModule) ExecuteAggregate(ctx context.Context, collectionName string, aggregateId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"aggregateId":    aggregateId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/aggregates/{aggregateId}/execute",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// Find performs GET /{version}/database/collections/{collectionName} (scope: project).
//
// "expandReferences": true (query) returns every reference field (user, role, term, record, file — at
// any nesting depth) as {"id": "...", "display": ...} — an array of them when the field is multiple —
// where "display" is the target's property named by the schema's displayField; a target that no
// longer exists gives "display": null, the id is always kept. Decode such a value into
// ExpandedReference. The caller must hold read on this collection AND on every source the published
// schema links to; one missing source refuses the whole read with CM-ERRORS-DATABASE-056 (context:
// SourceKind, Source, Fields, MissingPermissions) before any record is read. Off (default): the
// records exactly as stored, no source check.
func (m *DatabaseModule) Find(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// FindOne performs GET /{version}/database/collections/{collectionName}/{id} (scope: project).
//
// "expandReferences": true (query) returns every reference field (user, role, term, record, file — at
// any nesting depth) as {"id": "...", "display": ...} — an array of them when the field is multiple —
// where "display" is the target's property named by the schema's displayField; a target that no
// longer exists gives "display": null, the id is always kept. Decode such a value into
// ExpandedReference. The caller must hold read on this collection AND on every source the published
// schema links to; one missing source refuses the whole read with CM-ERRORS-DATABASE-056 (context:
// SourceKind, Source, Fields, MissingPermissions) before any record is read. Off (default): the
// records exactly as stored, no source check.
func (m *DatabaseModule) FindOne(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// InsertMany performs POST /{version}/database/collections/{collectionName}/many (scope: project).
//
// It adds several records ("documents" is a JSON array string).
//
// A caller with only own-record rights (createAsUser / updateOwn / deleteOwn) may call it; it then
// touches only that caller's records.
//
// An item that is not a JSON object is refused with CM-ERRORS-DATABASE-036 "Invalid record document"
// (its "Index" in the error context).
func (m *DatabaseModule) InsertMany(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/many",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// InsertOne performs POST /{version}/database/collections/{collectionName} (scope: project).
//
// It adds one record ("document" is the record as a JSON string).
//
// A body that is not a JSON object is refused with CM-ERRORS-DATABASE-036 "Invalid record document".
func (m *DatabaseModule) InsertOne(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ReplaceOne performs PUT /{version}/database/collections/{collectionName}/{id}/replace (scope: project).
//
// It replaces one record with "replacement" (a JSON string).
//
// A body that is not a JSON object is refused with CM-ERRORS-DATABASE-036 "Invalid record document".
//
// Soft-deleted records are not matched: such a record is "not found".
func (m *DatabaseModule) ReplaceOne(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/{id}/replace",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateMany performs PUT /{version}/database/collections/{collectionName}/many (scope: project).
//
// It applies "update" to every record that matches "filter" (a missing filter counts as "{}").
//
// "update" is the bare field document (e.g. {"price":12}); the gateway applies it with $set. A body
// with $ operators ($set, $inc, ...) is refused with CM-ERRORS-DATABASE-035.
//
// An empty filter ("{}") touches every record, so the gateway refuses it with CM-ERRORS-DATABASE-037
// unless "allRecords" is true.
//
// A caller with only own-record rights (createAsUser / updateOwn / deleteOwn) may call it; it then
// touches only that caller's records.
//
// "arrayFilters" (optional, a JSON string): a MongoDB arrayFilters ARRAY, one filter document per
// $[name] identifier used in an "update" path — e.g. "update": {"lines.$[line].qty":3} with
// "arrayFilters": [{"line.sku":"A-1"}] — to change one element of a nested array in place.
//
// Soft-deleted records are skipped.
func (m *DatabaseModule) UpdateMany(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/many",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateOne performs PUT /{version}/database/collections/{collectionName}/{id} (scope: project).
//
// It applies "update" (a JSON string) to one record.
//
// "update" is the bare field document (e.g. {"price":12}); the gateway applies it with $set. A body
// with $ operators ($set, $inc, ...) is refused with CM-ERRORS-DATABASE-035.
//
// "arrayFilters" (optional, a JSON string): a MongoDB arrayFilters ARRAY, one filter document per
// $[name] identifier used in an "update" path — e.g. "update": {"lines.$[line].qty":3} with
// "arrayFilters": [{"line.sku":"A-1"}] — to change one element of a nested array in place.
//
// Soft-deleted records are not matched: such a record is "not found".
func (m *DatabaseModule) UpdateOne(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/{id}",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// FindOwn performs GET /{version}/database/collections/{collectionName}/own (scope: project).
//
// It lists the records the signed-in user is responsible for ("filter", "pageSize", "startingAfter", "endingBefore", "schemaVersion" go in the query string).
//
// "expandReferences": true (query) returns every reference field (user, role, term, record, file — at
// any nesting depth) as {"id": "...", "display": ...} — an array of them when the field is multiple —
// where "display" is the target's property named by the schema's displayField; a target that no
// longer exists gives "display": null, the id is always kept. Decode such a value into
// ExpandedReference. The caller must hold read on this collection AND on every source the published
// schema links to; one missing source refuses the whole read with CM-ERRORS-DATABASE-056 (context:
// SourceKind, Source, Fields, MissingPermissions) before any record is read. Off (default): the
// records exactly as stored, no source check.
func (m *DatabaseModule) FindOwn(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/collections/{collectionName}/own",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// FindMergedTermTree performs GET /{version}/database/taxonomies/{taxonomyName}/merged-tree (scope: project).
//
// It returns the terms of a taxonomy merged with the terms of the taxonomies it depends on.
//
// It needs database:read on database:term:<id> of the taxonomy and of every nested taxonomy. An
// unknown taxonomy name answers CM-ERRORS-TAXONOMIES-010. More than 5000 terms answers
// CM-ERRORS-TAXONOMIES-011; read a sub-tree instead (rootTermId, depth).
func (m *DatabaseModule) FindMergedTermTree(ctx context.Context, taxonomyName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"taxonomyName": taxonomyName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/database/taxonomies/{taxonomyName}/merged-tree",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
