// Code generated by gen_modules.py. DO NOT EDIT.

package api

import (
	"context"

	"github.com/norbix-code/sdk-go/norbix/internal/transport"
)

// EchoModule groups the echo endpoints on the API.
type EchoModule struct{ t *transport.Transport }

// Echo performs GET /{version}/echo (scope: project).
func (m *EchoModule) Echo(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/echo",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
