// Code generated by gen_modules.py. DO NOT EDIT.

package api

import (
	"context"

	"github.com/norbix-code/sdk-go/norbix/internal/transport"
)

// FilesModule groups the files endpoints on the API.
type FilesModule struct{ t *transport.Transport }

// DeleteFileApi performs DELETE /{version}/files/{filesIntegrationId} (scope: project).
func (m *FilesModule) DeleteFileApi(ctx context.Context, filesIntegrationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"filesIntegrationId": filesIntegrationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/files/{filesIntegrationId}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ListFiles performs GET /{version}/files/{filesIntegrationId} (scope: project).
func (m *FilesModule) ListFiles(ctx context.Context, filesIntegrationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"filesIntegrationId": filesIntegrationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/files/{filesIntegrationId}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteManyFilesApi performs DELETE /{version}/files/{filesIntegrationId}/bulk (scope: project).
func (m *FilesModule) DeleteManyFilesApi(ctx context.Context, filesIntegrationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"filesIntegrationId": filesIntegrationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/files/{filesIntegrationId}/bulk",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// CommitUpload performs POST /{version}/files/{filesIntegrationId}/commit (scope: project).
func (m *FilesModule) CommitUpload(ctx context.Context, filesIntegrationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"filesIntegrationId": filesIntegrationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/files/{filesIntegrationId}/commit",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DownloadFileApi performs GET /{version}/files/{filesIntegrationId}/download (scope: project).
func (m *FilesModule) DownloadFileApi(ctx context.Context, filesIntegrationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"filesIntegrationId": filesIntegrationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/files/{filesIntegrationId}/download",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetFileInfo performs GET /{version}/files/{filesIntegrationId}/info (scope: project).
func (m *FilesModule) GetFileInfo(ctx context.Context, filesIntegrationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"filesIntegrationId": filesIntegrationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/files/{filesIntegrationId}/info",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSignedUrl performs GET /{version}/files/{filesIntegrationId}/sign (scope: project).
func (m *FilesModule) GetSignedUrl(ctx context.Context, filesIntegrationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"filesIntegrationId": filesIntegrationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/files/{filesIntegrationId}/sign",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RequestUploadUrl performs POST /{version}/files/{filesIntegrationId}/upload-url (scope: project).
func (m *FilesModule) RequestUploadUrl(ctx context.Context, filesIntegrationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"filesIntegrationId": filesIntegrationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/files/{filesIntegrationId}/upload-url",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ---------------------------------------------------------------------------
// The public file link (10b-files slice PUB). Hand-added by slice SDK-2.
// ---------------------------------------------------------------------------

// GetPublicFile performs GET /{version}/files/public/{publicId}/{name}
// (scope: unauthenticated) — it reads a file somebody made public.
//
// The gateway declares the route as /{version}/files/public/{PublicId}/{Name*} — written
// out here exactly as the gateway spells it, so the SDK coverage matrix can
// see that the two agree (knowledge.md K23).
//
// This call carries NO sign-in and NO project id: no Authorization header is
// sent, even when the client is signed in. That is what public means — the
// link has to work in an e-mail, in an <img src>, or in a browser on a
// stranger's phone, and the unguessable nbpf_… id is the whole credential.
//
// Pass a *[]byte as out to get the file's bytes:
//
//	var pdf []byte
//	err := client.API().Files().GetPublicFile(ctx, "nbpf_7hK2abc", "invoice.pdf", &pdf)
//
// name is the file's name for a file link, or the path inside the folder for a
// folder link ("2026/q1/report.pdf"); its slashes stay slashes. When the
// storage provider signs its own links (Amazon S3, Azure Blob, Google Cloud
// Storage) Norbix answers 302 and net/http follows it, so the bytes come from
// the provider and never pass through Norbix.
//
// Every miss is the same plain 404 — an unknown id, a name that does not
// match, a file made private again, a file gone from storage. A more precise
// answer would tell a stranger that the file is there.
func (m *FilesModule) GetPublicFile(ctx context.Context, publicId string, name string, out any) error {
	pathParams := map[string]string{
		"publicId": publicId,
		"name":     name,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/files/public/{publicId}/{name}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       nil,
		Scope:      transport.ScopeUnauthenticated,
	}, out)
}
