// Code generated by gen_modules.py. DO NOT EDIT.

package api

import (
	"context"

	"github.com/norbix-code/sdk-go/norbix/internal/transport"
)

// FilesModule groups the files endpoints on the API.
type FilesModule struct{ t *transport.Transport }

// DeleteFileApi performs DELETE /{version}/files/{filesIntegrationId} (scope: project).
func (m *FilesModule) DeleteFileApi(ctx context.Context, filesIntegrationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"filesIntegrationId": filesIntegrationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/files/{filesIntegrationId}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ListFiles performs GET /{version}/files/{filesIntegrationId} (scope: project).
func (m *FilesModule) ListFiles(ctx context.Context, filesIntegrationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"filesIntegrationId": filesIntegrationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/files/{filesIntegrationId}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteManyFilesApi performs DELETE /{version}/files/{filesIntegrationId}/bulk (scope: project).
func (m *FilesModule) DeleteManyFilesApi(ctx context.Context, filesIntegrationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"filesIntegrationId": filesIntegrationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/files/{filesIntegrationId}/bulk",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// CommitUpload performs POST /{version}/files/{filesIntegrationId}/commit (scope: project).
func (m *FilesModule) CommitUpload(ctx context.Context, filesIntegrationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"filesIntegrationId": filesIntegrationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/files/{filesIntegrationId}/commit",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DownloadFileApi performs GET /{version}/files/{filesIntegrationId}/download (scope: project).
func (m *FilesModule) DownloadFileApi(ctx context.Context, filesIntegrationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"filesIntegrationId": filesIntegrationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/files/{filesIntegrationId}/download",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetFileInfo performs GET /{version}/files/{filesIntegrationId}/info (scope: project).
func (m *FilesModule) GetFileInfo(ctx context.Context, filesIntegrationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"filesIntegrationId": filesIntegrationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/files/{filesIntegrationId}/info",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSignedUrl performs GET /{version}/files/{filesIntegrationId}/sign (scope: project).
func (m *FilesModule) GetSignedUrl(ctx context.Context, filesIntegrationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"filesIntegrationId": filesIntegrationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/files/{filesIntegrationId}/sign",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RequestUploadUrl performs POST /{version}/files/{filesIntegrationId}/upload-url (scope: project).
func (m *FilesModule) RequestUploadUrl(ctx context.Context, filesIntegrationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"filesIntegrationId": filesIntegrationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/files/{filesIntegrationId}/upload-url",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
