// Code generated by gen_modules.py. DO NOT EDIT.

package api

import (
	"context"

	"github.com/norbix-code/sdk-go/norbix/internal/transport"
)

// MembershipModule groups the membership endpoints on the API.
type MembershipModule struct{ t *transport.Transport }

// BlockUser performs PATCH /{version}/membership/users/block (scope: project).
func (m *MembershipModule) BlockUser(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users/block",
		Method:     "PATCH",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveSystemUserWithPermissions performs POST /{version}/membership/users/register/service (scope: project).
func (m *MembershipModule) SaveSystemUserWithPermissions(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users/register/service",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveGuestUser performs POST /{version}/membership/users/register/guest (scope: project).
func (m *MembershipModule) SaveGuestUser(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users/register/guest",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveUserNameUser performs POST /{version}/membership/users/register/user-name (scope: project).
func (m *MembershipModule) SaveUserNameUser(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users/register/user-name",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveEmailUser performs POST /{version}/membership/users/register/email (scope: project).
func (m *MembershipModule) SaveEmailUser(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users/register/email",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SavePhoneUser performs POST /{version}/membership/users/register/phone (scope: project).
func (m *MembershipModule) SavePhoneUser(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users/register/phone",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SavePhoneUserNameWithPermissions performs POST /{version}/membership/users/register/phone-with-permissions (scope: project).
func (m *MembershipModule) SavePhoneUserNameWithPermissions(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users/register/phone-with-permissions",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveEmailUserNameWithPermissions performs POST /{version}/membership/users/register/email-with-permissions (scope: project).
func (m *MembershipModule) SaveEmailUserNameWithPermissions(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users/register/email-with-permissions",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveUserNameWithPermissions performs POST /{version}/membership/users/register/user-name-with-permissions (scope: project).
func (m *MembershipModule) SaveUserNameWithPermissions(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users/register/user-name-with-permissions",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteUser performs DELETE /{version}/membership/users (scope: project).
func (m *MembershipModule) DeleteUser(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users",
		Method:     "DELETE",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetUser performs GET /{version}/membership/users/{id} (scope: project).
func (m *MembershipModule) GetUser(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetUsers performs GET /{version}/membership/users (scope: project).
func (m *MembershipModule) GetUsers(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetUserPreferences performs GET /{version}/membership/users/{id}/preferences (scope: project).
func (m *MembershipModule) GetUserPreferences(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users/{id}/preferences",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// InviteUser performs POST /{version}/membership/users/invite (scope: project).
func (m *MembershipModule) InviteUser(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users/invite",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// AssignRolePermissions performs PUT /{version}/membership/users/assign-roles (scope: project).
func (m *MembershipModule) AssignRolePermissions(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users/assign-roles",
		Method:     "PUT",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UnblockUser performs PATCH /{version}/membership/users/unblock (scope: project).
func (m *MembershipModule) UnblockUser(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users/unblock",
		Method:     "PATCH",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateUser performs PUT /{version}/membership/users (scope: project).
func (m *MembershipModule) UpdateUser(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users",
		Method:     "PUT",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateUserPreferences performs PUT /{version}/membership/users/{id}/preferences (scope: project).
func (m *MembershipModule) UpdateUserPreferences(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users/{id}/preferences",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ConfirmEmailVerification performs POST /{version}/membership/userauth/email/confirm-verification (scope: project).
func (m *MembershipModule) ConfirmEmailVerification(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/userauth/email/confirm-verification",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// StartEmailVerification performs POST /{version}/membership/userauth/email/start-verification (scope: project).
func (m *MembershipModule) StartEmailVerification(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/userauth/email/start-verification",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// HasPasskey performs POST /{version}/membership/userauth/has-passkey (scope: project).
func (m *MembershipModule) HasPasskey(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/userauth/has-passkey",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// PasskeyLogout performs POST /{version}/membership/userauth/logout (scope: project).
func (m *MembershipModule) PasskeyLogout(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/userauth/logout",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// PasskeyAuthenticationOptions performs POST /{version}/membership/userauth/passkey/authentication-options (scope: project).
func (m *MembershipModule) PasskeyAuthenticationOptions(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/userauth/passkey/authentication-options",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// PasskeyRegistrationOptions performs POST /{version}/membership/userauth/passkey/registration-options (scope: project).
func (m *MembershipModule) PasskeyRegistrationOptions(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/userauth/passkey/registration-options",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// VerifyPasskeyAuthentication performs POST /{version}/membership/userauth/passkey/verify-authentication (scope: project).
func (m *MembershipModule) VerifyPasskeyAuthentication(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/userauth/passkey/verify-authentication",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// VerifyPasskeyRegistration performs POST /{version}/membership/userauth/passkey/verify-registration (scope: project).
func (m *MembershipModule) VerifyPasskeyRegistration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/userauth/passkey/verify-registration",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ListPasskeys performs GET /{version}/membership/userauth/passkeys (scope: project).
func (m *MembershipModule) ListPasskeys(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/userauth/passkeys",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RenamePasskey performs POST /{version}/membership/userauth/passkeys/{CredentialId}/rename (scope: project).
func (m *MembershipModule) RenamePasskey(ctx context.Context, credentialId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"CredentialId": credentialId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/userauth/passkeys/{CredentialId}/rename",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RevokePasskey performs POST /{version}/membership/userauth/passkeys/{CredentialId}/revoke (scope: project).
func (m *MembershipModule) RevokePasskey(ctx context.Context, credentialId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"CredentialId": credentialId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/userauth/passkeys/{CredentialId}/revoke",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ConsumeMagicLink performs POST /{version}/membership/userauth/recovery/magic-link/consume (scope: project).
func (m *MembershipModule) ConsumeMagicLink(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/userauth/recovery/magic-link/consume",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RequestMagicLink performs POST /{version}/membership/userauth/recovery/magic-link/request (scope: project).
func (m *MembershipModule) RequestMagicLink(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/userauth/recovery/magic-link/request",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UseRecoveryCode performs POST /{version}/membership/userauth/recovery/use-code (scope: project).
func (m *MembershipModule) UseRecoveryCode(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/userauth/recovery/use-code",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RefreshPasskeyToken performs POST /{version}/membership/userauth/token/refresh (scope: project).
func (m *MembershipModule) RefreshPasskeyToken(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/userauth/token/refresh",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// LinkIdentity performs POST /{version}/membership/users/{userId}/link-identity (scope: project).
func (m *MembershipModule) LinkIdentity(ctx context.Context, userId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"userId": userId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetAPI,
		Path:       "/{version}/membership/users/{userId}/link-identity",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
