// Code generated by gen_modules.py. DO NOT EDIT.

// Package api exposes the Norbix API endpoint modules.
package api

import "github.com/norbix-code/sdk-go/v2/norbix/internal/transport"

// Namespace bundles every API module.
type Namespace struct {
	Ai         *AiModule
	Database   *DatabaseModule
	Echo       *EchoModule
	Files      *FilesModule
	Membership *MembershipModule
	Public     *PublicModule
}

// NewNamespace wires every module to the shared transport.
func NewNamespace(t *transport.Transport) *Namespace {
	return &Namespace{
		Ai:         &AiModule{t: t},
		Database:   &DatabaseModule{t: t},
		Echo:       &EchoModule{t: t},
		Files:      &FilesModule{t: t},
		Membership: &MembershipModule{t: t},
		Public:     &PublicModule{t: t},
	}
}
