// Hand-written, not generated (10b-files slice API-TEST, issue #39).
//
// dtos.go is generated by gen_dtos.py (DO NOT EDIT), and the API contract it
// was generated from does not have these three types yet. They mirror the
// gateway's TestFilesIntegrationRequest, TestFilesIntegrationResponse and
// IntegrationTestResultItemDto. If a regeneration of dtos.go adds them, the
// build fails with "redeclared" and this file should simply be deleted.

package dtos

// TestFilesIntegrationRequest DTO.
type TestFilesIntegrationRequest struct {
	CodeMashRequestBase
	FilesIntegrationId string `json:"filesIntegrationId,omitempty"`
}

// TestFilesIntegrationResponse DTO.
type TestFilesIntegrationResponse struct {
	ResponseBase
	Items []*IntegrationTestResultItemDto `json:"items,omitempty"`
}

// IntegrationTestResultItemDto DTO: the outcome of one step of the probe.
type IntegrationTestResultItemDto struct {
	Operation string   `json:"operation,omitempty"`
	Result    string   `json:"result,omitempty"`
	Errors    []string `json:"errors,omitempty"`
}
