// Code generated by gen_modules.py. DO NOT EDIT.

package hub

import (
	"context"

	"github.com/norbix-code/sdk-go/v2/norbix/internal/transport"
)

// AccountModule groups the account endpoints on the HUB.
type AccountModule struct{ t *transport.Transport }

// GetAccountProfile performs GET /{version}/account/profile (scope: account).
func (m *AccountModule) GetAccountProfile(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/profile",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateAccountProfile performs PUT /{version}/account/profile (scope: account).
func (m *AccountModule) UpdateAccountProfile(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/profile",
		Method:     "PUT",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// ResendAccountVerificationToken performs GET /{version}/account/verify/resend (scope: account).
func (m *AccountModule) ResendAccountVerificationToken(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/verify/resend",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetAccountStatus performs GET /{version}/account/status (scope: account).
func (m *AccountModule) GetAccountStatus(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/status",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// CreateStripeCheckoutSession performs POST /{version}/account/stripe/create-checkout-session (scope: account).
func (m *AccountModule) CreateStripeCheckoutSession(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/stripe/create-checkout-session",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetStripeBillingPortalUrl performs POST /{version}/account/stripe/get-portal-url (scope: account).
func (m *AccountModule) GetStripeBillingPortalUrl(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/stripe/get-portal-url",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// CreateTeamMemberFromInvitation performs POST /{version}/account/team/member (scope: account).
func (m *AccountModule) CreateTeamMemberFromInvitation(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/team/member",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// VerifyAccount performs GET /{version}/account/verify (scope: account).
func (m *AccountModule) VerifyAccount(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/verify",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// DeleteNotificationsGroup performs DELETE /{version}/account/projects/{projectId}/notifications/settings/group (scope: account).
func (m *AccountModule) DeleteNotificationsGroup(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/notifications/settings/group",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// DeleteNotificationsTag performs DELETE /{version}/account/projects/{projectId}/notifications/settings/tag (scope: account).
func (m *AccountModule) DeleteNotificationsTag(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/notifications/settings/tag",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// RemoveTagFromNotificationsGroup performs DELETE /{version}/account/projects/{projectId}/notifications/settings/group/tag (scope: account).
func (m *AccountModule) RemoveTagFromNotificationsGroup(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/notifications/settings/group/tag",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// SaveNotificationsGroup performs POST /{version}/account/projects/{projectId}/notifications/settings/group (scope: account).
func (m *AccountModule) SaveNotificationsGroup(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/notifications/settings/group",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// SaveNotificationsTag performs POST /{version}/account/projects/{projectId}/notifications/settings/tag (scope: account).
func (m *AccountModule) SaveNotificationsTag(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/notifications/settings/tag",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// CreateProject performs POST /{version}/account/projects (scope: account).
func (m *AccountModule) CreateProject(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// DeleteProject performs DELETE /{version}/account/projects/{projectId} (scope: account).
func (m *AccountModule) DeleteProject(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetProject performs GET /{version}/account/projects/{projectId} (scope: account).
func (m *AccountModule) GetProject(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetProjects performs GET /{version}/account/projects (scope: account).
func (m *AccountModule) GetProjects(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetAccountRegions performs GET /{version}/account/regions (scope: account).
func (m *AccountModule) GetAccountRegions(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/regions",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetProjectTokens performs GET /{version}/account/projects/{projectId}/tokens (scope: account).
func (m *AccountModule) GetProjectTokens(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/tokens",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectAccentColor performs PATCH /{version}/account/projects/{projectId}/settings/accent-color (scope: account).
func (m *AccountModule) UpdateProjectAccentColor(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/accent-color",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectIcon performs PATCH /{version}/account/projects/{projectId}/settings/icon (scope: account).
func (m *AccountModule) UpdateProjectIcon(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/icon",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectLogo performs PATCH /{version}/account/projects/{projectId}/settings/logo (scope: account).
func (m *AccountModule) UpdateProjectLogo(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/logo",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectMainColor performs PATCH /{version}/account/projects/{projectId}/settings/main-color (scope: account).
func (m *AccountModule) UpdateProjectMainColor(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/main-color",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectAllowedOrigins performs PATCH /{version}/account/projects/{projectId}/settings/origins (scope: account).
func (m *AccountModule) UpdateProjectAllowedOrigins(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/origins",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectDefaultLanguage performs PATCH /{version}/account/projects/{projectId}/settings/default-language (scope: account).
func (m *AccountModule) UpdateProjectDefaultLanguage(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/default-language",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectDescription performs PATCH /{version}/account/projects/{projectId}/settings/description (scope: account).
func (m *AccountModule) UpdateProjectDescription(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/description",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// DisableProject performs PATCH /{version}/account/projects/{projectId}/disable (scope: account).
func (m *AccountModule) DisableProject(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/disable",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// EnableProject performs PATCH /{version}/account/projects/{projectId}/enable (scope: account).
func (m *AccountModule) EnableProject(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/enable",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectLanguages performs PATCH /{version}/account/projects/{projectId}/settings/languages (scope: account).
func (m *AccountModule) UpdateProjectLanguages(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/languages",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// CheckProjectLanguages performs POST /{version}/account/projects/{projectId}/settings/languages/check (scope: account).
//
// It lists the Email, Push and SMS templates that miss a project language.
// Send the proposed "defaultLanguage" and/or "languages" to check a change
// before UpdateProjectLanguages saves it; send neither to check the current
// settings. The response carries "templates": one entry per template with
// its "module", "templateId", "templateName" and "missingLanguages"
// (dtos.CheckProjectLanguagesResponse).
func (m *AccountModule) CheckProjectLanguages(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/languages/check",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectUrl performs PATCH /{version}/account/projects/{projectId}/settings/url (scope: account).
func (m *AccountModule) UpdateProjectUrl(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/url",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectName performs PATCH /{version}/account/projects/{projectId}/settings/name (scope: account).
func (m *AccountModule) UpdateProjectName(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/name",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectRegions performs PATCH /{version}/account/projects/{projectId}/settings/regions (scope: account).
func (m *AccountModule) UpdateProjectRegions(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/regions",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// CreateAccount performs POST /{version}/account (scope: account).
func (m *AccountModule) CreateAccount(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetAccountCollaborators performs GET /{version}/account/collaborators (scope: project).
// It lists the account owner and team members. The gateway takes the account
// from the signed-in session, so AccountID is not needed. Page with the flat
// fields "pageSize" (default 20), "startingAfter" and "endingBefore"; set
// "projectId" (without "includeAccountOwner") for one project's collaborators.
func (m *AccountModule) GetAccountCollaborators(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/collaborators",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetMyAccountUserProfile performs GET /{version}/account/me (scope: project).
// It reads the signed-in account user's own profile (dtos.GetMyAccountUserProfileResponse),
// including the phone saved with UpdateMyAccountUserPhone.
func (m *AccountModule) GetMyAccountUserProfile(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/me",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateMyAccountUserPhone performs PUT /{version}/account/me/phone (scope: project).
// It saves the signed-in account user's phone ("phone", E.164 format such as
// "+37060000000"; an empty value clears it). "Account users" SMS campaigns
// send to this number.
func (m *AccountModule) UpdateMyAccountUserPhone(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/me/phone",
		Method:     "PUT",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SendInviteToTeamMember performs POST /{version}/account/team/member/invite (scope: account).
func (m *AccountModule) SendInviteToTeamMember(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/team/member/invite",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetLicenses performs GET /{version}/account/licenses (scope: account).
func (m *AccountModule) GetLicenses(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/licenses",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetProjectAiSettings performs GET /{version}/account/projects/{projectId}/ai/settings (scope: project).
func (m *AccountModule) GetProjectAiSettings(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/ai/settings",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateProjectAiSettings performs PUT /{version}/account/projects/{projectId}/ai/settings (scope: project).
func (m *AccountModule) UpdateProjectAiSettings(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/ai/settings",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// CreateProjectAiAssistant performs POST /{version}/account/projects/{projectId}/ai/assistants (scope: project).
func (m *AccountModule) CreateProjectAiAssistant(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/ai/assistants",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateProjectAiAssistant performs PUT /{version}/account/projects/{projectId}/ai/assistants/{assistantId} (scope: project).
func (m *AccountModule) UpdateProjectAiAssistant(ctx context.Context, projectId string, assistantId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId":   projectId,
		"assistantId": assistantId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/ai/assistants/{assistantId}",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteProjectAiAssistant performs DELETE /{version}/account/projects/{projectId}/ai/assistants/{assistantId} (scope: project).
func (m *AccountModule) DeleteProjectAiAssistant(ctx context.Context, projectId string, assistantId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId":   projectId,
		"assistantId": assistantId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/ai/assistants/{assistantId}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetProjectAiUsage performs GET /{version}/account/projects/{projectId}/ai/usage (scope: project).
func (m *AccountModule) GetProjectAiUsage(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/ai/usage",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SetAdminPortalEnabled performs PUT /{version}/account/projects/{projectId}/admin-portal/enabled (scope: project).
func (m *AccountModule) SetAdminPortalEnabled(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/admin-portal/enabled",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ---------------------------------------------------------------------------
// Project settings and Admin Portal (project audit, item E1). Hand-added.
// ---------------------------------------------------------------------------

// UpdateProjectAdminUrl performs PATCH /{version}/account/projects/{projectId}/settings/admin-url (scope: account).
// It overrides the project's Admin Portal address; an empty value restores the
// canonical one.
func (m *AccountModule) UpdateProjectAdminUrl(ctx context.Context, projectId string, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/admin-url",
		Method:     "PATCH",
		PathParams: map[string]string{"projectId": projectId},
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectLegalDocuments performs PATCH /{version}/account/projects/{projectId}/settings/legal (scope: account).
// It saves the project's Terms and Privacy Policy as Markdown; an empty value
// clears that document.
func (m *AccountModule) UpdateProjectLegalDocuments(ctx context.Context, projectId string, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/legal",
		Method:     "PATCH",
		PathParams: map[string]string{"projectId": projectId},
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectExposeLegal performs PATCH /{version}/account/projects/{projectId}/settings/legal/expose (scope: account).
// It turns the public legal links (api.PublicModule.GetPublicProjectLegal) on or off.
func (m *AccountModule) UpdateProjectExposeLegal(ctx context.Context, projectId string, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/legal/expose",
		Method:     "PATCH",
		PathParams: map[string]string{"projectId": projectId},
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectExposeBrand performs PATCH /{version}/account/projects/{projectId}/settings/brand/expose (scope: account).
// It sets whether the brand (name, colors, logo, icon) is returned by the public
// Admin Portal config (api.PublicModule.GetPublicProjectConfig). On by default.
func (m *AccountModule) UpdateProjectExposeBrand(ctx context.Context, projectId string, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/brand/expose",
		Method:     "PATCH",
		PathParams: map[string]string{"projectId": projectId},
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectExposeAuth performs PATCH /{version}/account/projects/{projectId}/settings/auth/expose (scope: account).
// It sets whether the sign-in methods and password policy are returned by the public
// Admin Portal config (api.PublicModule.GetPublicProjectConfig). Off by default.
func (m *AccountModule) UpdateProjectExposeAuth(ctx context.Context, projectId string, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/auth/expose",
		Method:     "PATCH",
		PathParams: map[string]string{"projectId": projectId},
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// AssignAdminPortalServiceUser performs PUT /{version}/account/projects/{projectId}/settings/admin-portal/service-user (scope: account).
// It makes an existing service user the project's Admin Portal service user.
func (m *AccountModule) AssignAdminPortalServiceUser(ctx context.Context, projectId string, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/admin-portal/service-user",
		Method:     "PUT",
		PathParams: map[string]string{"projectId": projectId},
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetAdminPortalStructure performs GET /{version}/account/projects/{projectId}/admin-portal/structure (scope: project).
// It returns the Admin Portal layout for the project's service user.
func (m *AccountModule) GetAdminPortalStructure(ctx context.Context, projectId string, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/admin-portal/structure",
		Method:     "GET",
		PathParams: map[string]string{"projectId": projectId},
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ---------------------------------------------------------------------------
// AI service users (project audit, item E1). Hand-added.
//
// A service user is a scoped identity for an AI agent (Claude Code, Cursor, …).
// Its API key is shown ONCE, in the answer of CreateAiServiceUser and
// RotateAiServiceUserKey; later reads show only a key id and a hint.
// ---------------------------------------------------------------------------

// CreateAiServiceUser performs POST /{version}/account/ai/service-users (scope: account).
func (m *AccountModule) CreateAiServiceUser(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target: transport.TargetHub,
		Path:   "/{version}/account/ai/service-users",
		Method: "POST",
		Body:   req,
		Scope:  transport.ScopeAccount,
	}, out)
}

// ListAiServiceUsers performs GET /{version}/account/ai/service-users (scope: account).
func (m *AccountModule) ListAiServiceUsers(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target: transport.TargetHub,
		Path:   "/{version}/account/ai/service-users",
		Method: "GET",
		Body:   req,
		Scope:  transport.ScopeAccount,
	}, out)
}

// DeleteAiServiceUser performs DELETE /{version}/account/ai/service-users/{Id} (scope: account).
// It deletes the service user and every one of its keys.
func (m *AccountModule) DeleteAiServiceUser(ctx context.Context, id string, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/ai/service-users/{Id}",
		Method:     "DELETE",
		PathParams: map[string]string{"Id": id},
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// RotateAiServiceUserKey performs POST /{version}/account/ai/service-users/{Id}/keys (scope: account).
// It issues a new key; with "revokeKeyId" in req it also revokes that old key.
func (m *AccountModule) RotateAiServiceUserKey(ctx context.Context, id string, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/ai/service-users/{Id}/keys",
		Method:     "POST",
		PathParams: map[string]string{"Id": id},
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// RevokeAiServiceUserKey performs DELETE /{version}/account/ai/service-users/{Id}/keys/{KeyId} (scope: account).
func (m *AccountModule) RevokeAiServiceUserKey(ctx context.Context, id string, keyId string, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/ai/service-users/{Id}/keys/{KeyId}",
		Method:     "DELETE",
		PathParams: map[string]string{"Id": id, "KeyId": keyId},
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// ---------------------------------------------------------------------------
// Developer MCP endpoint (project audit, item E1). Hand-added.
//
// /{version}/account/mcp is the Hub's Model Context Protocol server. Most
// callers are MCP clients (Claude, Cursor) and never use these methods; they
// exist for tests and scripts that speak JSON-RPC directly.
//
// Limits of this transport: the answer is read in full before the call
// returns, and response headers are not returned — so the Mcp-Session-Id the
// server sends back on "initialize" cannot be read here, and McpOpenStream
// returns only when the server closes the stream or the timeout is reached.
// ---------------------------------------------------------------------------

// McpSessionHeader is the header that names an MCP session.
const McpSessionHeader = "Mcp-Session-Id"

func mcpHeaders(sessionId string) map[string]string {
	h := map[string]string{"Accept": "application/json, text/event-stream"}
	if sessionId != "" {
		h[McpSessionHeader] = sessionId
	}
	return h
}

// Mcp performs POST /{version}/account/mcp (scope: project).
// msg is one JSON-RPC message, e.g.
// {"jsonrpc":"2.0","id":1,"method":"tools/list"}. sessionId may be empty
// (for "initialize"). Pass a *[]byte as out when the server may answer with an
// SSE stream instead of JSON.
func (m *AccountModule) Mcp(ctx context.Context, sessionId string, msg map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:  transport.TargetHub,
		Path:    "/{version}/account/mcp",
		Method:  "POST",
		Body:    msg,
		Scope:   transport.ScopeProject,
		Headers: mcpHeaders(sessionId),
	}, out)
}

// McpOpenStream performs GET /{version}/account/mcp (scope: project).
// It opens the server-to-client SSE stream of a session. Pass a *[]byte as out.
func (m *AccountModule) McpOpenStream(ctx context.Context, sessionId string, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:  transport.TargetHub,
		Path:    "/{version}/account/mcp",
		Method:  "GET",
		Scope:   transport.ScopeProject,
		Headers: mcpHeaders(sessionId),
	}, out)
}

// McpEndSession performs DELETE /{version}/account/mcp (scope: project).
// It ends the session named by sessionId.
func (m *AccountModule) McpEndSession(ctx context.Context, sessionId string, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:  transport.TargetHub,
		Path:    "/{version}/account/mcp",
		Method:  "DELETE",
		Scope:   transport.ScopeProject,
		Headers: mcpHeaders(sessionId),
	}, out)
}
