// Code generated by gen_modules.py. DO NOT EDIT.

package hub

import (
	"context"

	"github.com/norbix-code/sdk-go/norbix/internal/transport"
)

// AccountModule groups the account endpoints on the HUB.
type AccountModule struct{ t *transport.Transport }

// GetAccountProfile performs GET /{version}/account/profile (scope: account).
func (m *AccountModule) GetAccountProfile(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/profile",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateAccountProfile performs PUT /{version}/account/profile (scope: account).
func (m *AccountModule) UpdateAccountProfile(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/profile",
		Method:     "PUT",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// ResendAccountVerificationToken performs GET /{version}/account/verify/resend (scope: account).
func (m *AccountModule) ResendAccountVerificationToken(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/verify/resend",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetAccountStatus performs GET /{version}/account/status (scope: account).
func (m *AccountModule) GetAccountStatus(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/status",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// CreateStripeCheckoutSession performs POST /{version}/account/stripe/create-checkout-session (scope: account).
func (m *AccountModule) CreateStripeCheckoutSession(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/stripe/create-checkout-session",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetStripeBillingPortalUrl performs POST /{version}/account/stripe/get-portal-url (scope: account).
func (m *AccountModule) GetStripeBillingPortalUrl(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/stripe/get-portal-url",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// CreateTeamMemberFromInvitation performs POST /{version}/account/team/member (scope: account).
func (m *AccountModule) CreateTeamMemberFromInvitation(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/team/member",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// VerifyAccount performs GET /{version}/account/verify (scope: account).
func (m *AccountModule) VerifyAccount(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/verify",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// DeleteNotificationsGroup performs DELETE /{version}/account/projects/{projectId}/notifications/settings/group (scope: account).
func (m *AccountModule) DeleteNotificationsGroup(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/notifications/settings/group",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// DeleteNotificationsTag performs DELETE /{version}/account/projects/{projectId}/notifications/settings/tag (scope: account).
func (m *AccountModule) DeleteNotificationsTag(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/notifications/settings/tag",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// RemoveTagFromNotificationsGroup performs DELETE /{version}/account/projects/{projectId}/notifications/settings/group/tag (scope: account).
func (m *AccountModule) RemoveTagFromNotificationsGroup(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/notifications/settings/group/tag",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// SaveNotificationsGroup performs POST /{version}/account/projects/{projectId}/notifications/settings/group (scope: account).
func (m *AccountModule) SaveNotificationsGroup(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/notifications/settings/group",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// SaveNotificationsTag performs POST /{version}/account/projects/{projectId}/notifications/settings/tag (scope: account).
func (m *AccountModule) SaveNotificationsTag(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/notifications/settings/tag",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// CreateProject performs POST /{version}/account/projects (scope: account).
func (m *AccountModule) CreateProject(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// DeleteProject performs DELETE /{version}/account/projects/{projectId} (scope: account).
func (m *AccountModule) DeleteProject(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetProject performs GET /{version}/account/projects/{projectId} (scope: account).
func (m *AccountModule) GetProject(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetProjects performs GET /{version}/account/projects (scope: account).
func (m *AccountModule) GetProjects(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetAccountRegions performs GET /{version}/account/regions (scope: account).
func (m *AccountModule) GetAccountRegions(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/regions",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetProjectTokens performs GET /{version}/account/projects/{projectId}/tokens (scope: account).
func (m *AccountModule) GetProjectTokens(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/tokens",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectAccentColor performs PATCH /{version}/account/projects/{projectId}/settings/accent-color (scope: account).
func (m *AccountModule) UpdateProjectAccentColor(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/accent-color",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectIcon performs PATCH /{version}/account/projects/{projectId}/settings/icon (scope: account).
func (m *AccountModule) UpdateProjectIcon(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/icon",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectLogo performs PATCH /{version}/account/projects/{projectId}/settings/logo (scope: account).
func (m *AccountModule) UpdateProjectLogo(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/logo",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectMainColor performs PATCH /{version}/account/projects/{projectId}/settings/main-color (scope: account).
func (m *AccountModule) UpdateProjectMainColor(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/main-color",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectAllowedOrigins performs PATCH /{version}/account/projects/{projectId}/settings/origins (scope: account).
func (m *AccountModule) UpdateProjectAllowedOrigins(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/origins",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectDefaultLanguage performs PATCH /{version}/account/projects/{projectId}/settings/default-language (scope: account).
func (m *AccountModule) UpdateProjectDefaultLanguage(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/default-language",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectDescription performs PATCH /{version}/account/projects/{projectId}/settings/description (scope: account).
func (m *AccountModule) UpdateProjectDescription(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/description",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// DisableProject performs PATCH /{version}/account/projects/{projectId}/disable (scope: account).
func (m *AccountModule) DisableProject(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/disable",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// EnableProject performs PATCH /{version}/account/projects/{projectId}/enable (scope: account).
func (m *AccountModule) EnableProject(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/enable",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectLanguages performs PATCH /{version}/account/projects/{projectId}/settings/languages (scope: account).
func (m *AccountModule) UpdateProjectLanguages(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/languages",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectUrl performs PATCH /{version}/account/projects/{projectId}/settings/url (scope: account).
func (m *AccountModule) UpdateProjectUrl(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/url",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectName performs PATCH /{version}/account/projects/{projectId}/settings/name (scope: account).
func (m *AccountModule) UpdateProjectName(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/name",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// UpdateProjectRegions performs PATCH /{version}/account/projects/{projectId}/settings/regions (scope: account).
func (m *AccountModule) UpdateProjectRegions(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/regions",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// CreateAccount performs POST /{version}/account (scope: account).
func (m *AccountModule) CreateAccount(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetAccountCollaborators performs GET /{version}/account/collaborators (scope: account).
func (m *AccountModule) GetAccountCollaborators(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/collaborators",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// SendInviteToTeamMember performs POST /{version}/account/team/member/invite (scope: account).
func (m *AccountModule) SendInviteToTeamMember(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/team/member/invite",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// GetLicenses performs GET /{version}/account/licenses (scope: account).
func (m *AccountModule) GetLicenses(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/licenses",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// AskChat performs POST /{version}/account/chat/complete (scope: account).
func (m *AccountModule) AskChat(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/chat/complete",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}
