// Code generated by gen_modules.py. DO NOT EDIT.

package hub

import (
	"context"

	"github.com/norbix-code/sdk-go/norbix/internal/transport"
)

// CodeModule groups the code endpoints on the HUB.
type CodeModule struct{ t *transport.Transport }

// DisableCode performs GET /{version}/code/disable (scope: project).
func (m *CodeModule) DisableCode(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/disable",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableCode performs GET /{version}/code/enable (scope: project).
func (m *CodeModule) EnableCode(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/enable",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetCodeIntegrations performs GET /{version}/code/integrations (scope: project).
func (m *CodeModule) GetCodeIntegrations(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/integrations",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveCodeIntegration performs POST /{version}/code/integrations (scope: project).
func (m *CodeModule) SaveCodeIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/integrations",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ConfirmCodeIntegrationHumanDelivery performs POST /{version}/code/integrations/confirm-human-delivery (scope: project).
func (m *CodeModule) ConfirmCodeIntegrationHumanDelivery(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/integrations/confirm-human-delivery",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// TestCodeIntegration performs POST /{version}/code/integrations/test (scope: project).
func (m *CodeModule) TestCodeIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/integrations/test",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteCodeIntegration performs DELETE /{version}/code/integrations/{Id} (scope: project).
func (m *CodeModule) DeleteCodeIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/integrations/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SetCodeIntegrationAsDefault performs PUT /{version}/code/integrations/{Id}/default (scope: project).
func (m *CodeModule) SetCodeIntegrationAsDefault(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/integrations/{Id}/default",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisableCodeIntegration performs PUT /{version}/code/integrations/{Id}/disable (scope: project).
func (m *CodeModule) DisableCodeIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/integrations/{Id}/disable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableCodeIntegration performs PUT /{version}/code/integrations/{Id}/enable (scope: project).
func (m *CodeModule) EnableCodeIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/integrations/{Id}/enable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetCodeIntegration performs GET /{version}/code/integrations/{id} (scope: project).
func (m *CodeModule) GetCodeIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/integrations/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetMarketplaceIntegrations performs GET /{version}/code/marketplace/integrations (scope: project).
func (m *CodeModule) GetMarketplaceIntegrations(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/marketplace/integrations",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveMarketplaceIntegration performs POST /{version}/code/marketplace/integrations (scope: project).
func (m *CodeModule) SaveMarketplaceIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/marketplace/integrations",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteMarketplaceIntegration performs DELETE /{version}/code/marketplace/integrations/{IntegrationViewId} (scope: project).
func (m *CodeModule) DeleteMarketplaceIntegration(ctx context.Context, integrationViewId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"IntegrationViewId": integrationViewId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/marketplace/integrations/{IntegrationViewId}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetMarketplaceIntegration performs GET /{version}/code/marketplace/integrations/{IntegrationViewId} (scope: project).
func (m *CodeModule) GetMarketplaceIntegration(ctx context.Context, integrationViewId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"IntegrationViewId": integrationViewId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/marketplace/integrations/{IntegrationViewId}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetMarketplaceBindings performs GET /{version}/code/marketplace/integrations/{IntegrationViewId}/bindings (scope: project).
func (m *CodeModule) GetMarketplaceBindings(ctx context.Context, integrationViewId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"IntegrationViewId": integrationViewId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/marketplace/integrations/{IntegrationViewId}/bindings",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveMarketplaceFunctionBinding performs POST /{version}/code/marketplace/integrations/{IntegrationViewId}/bindings (scope: project).
func (m *CodeModule) SaveMarketplaceFunctionBinding(ctx context.Context, integrationViewId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"IntegrationViewId": integrationViewId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/marketplace/integrations/{IntegrationViewId}/bindings",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteMarketplaceFunctionBinding performs DELETE /{version}/code/marketplace/integrations/{IntegrationViewId}/bindings/{BindingViewId} (scope: project).
func (m *CodeModule) DeleteMarketplaceFunctionBinding(ctx context.Context, integrationViewId string, bindingViewId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"IntegrationViewId": integrationViewId,
		"BindingViewId":     bindingViewId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/marketplace/integrations/{IntegrationViewId}/bindings/{BindingViewId}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetMarketplaceBinding performs GET /{version}/code/marketplace/integrations/{IntegrationViewId}/bindings/{BindingViewId} (scope: project).
func (m *CodeModule) GetMarketplaceBinding(ctx context.Context, integrationViewId string, bindingViewId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"IntegrationViewId": integrationViewId,
		"BindingViewId":     bindingViewId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/marketplace/integrations/{IntegrationViewId}/bindings/{BindingViewId}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisableMarketplaceFunctionBinding performs POST /{version}/code/marketplace/integrations/{IntegrationViewId}/bindings/{BindingViewId}/disable (scope: project).
func (m *CodeModule) DisableMarketplaceFunctionBinding(ctx context.Context, integrationViewId string, bindingViewId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"IntegrationViewId": integrationViewId,
		"BindingViewId":     bindingViewId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/marketplace/integrations/{IntegrationViewId}/bindings/{BindingViewId}/disable",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableMarketplaceFunctionBinding performs POST /{version}/code/marketplace/integrations/{IntegrationViewId}/bindings/{BindingViewId}/enable (scope: project).
func (m *CodeModule) EnableMarketplaceFunctionBinding(ctx context.Context, integrationViewId string, bindingViewId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"IntegrationViewId": integrationViewId,
		"BindingViewId":     bindingViewId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/marketplace/integrations/{IntegrationViewId}/bindings/{BindingViewId}/enable",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// InvokeMarketplaceFunctionBinding performs POST /{version}/code/marketplace/integrations/{IntegrationViewId}/bindings/{BindingViewId}/invoke (scope: project).
func (m *CodeModule) InvokeMarketplaceFunctionBinding(ctx context.Context, integrationViewId string, bindingViewId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"IntegrationViewId": integrationViewId,
		"BindingViewId":     bindingViewId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/marketplace/integrations/{IntegrationViewId}/bindings/{BindingViewId}/invoke",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetMarketplaceBindingTokens performs GET /{version}/code/marketplace/integrations/{IntegrationViewId}/bindings/{BindingViewId}/tokens (scope: project).
func (m *CodeModule) GetMarketplaceBindingTokens(ctx context.Context, integrationViewId string, bindingViewId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"IntegrationViewId": integrationViewId,
		"BindingViewId":     bindingViewId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/marketplace/integrations/{IntegrationViewId}/bindings/{BindingViewId}/tokens",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisableMarketplaceIntegration performs POST /{version}/code/marketplace/integrations/{IntegrationViewId}/disable (scope: project).
func (m *CodeModule) DisableMarketplaceIntegration(ctx context.Context, integrationViewId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"IntegrationViewId": integrationViewId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/marketplace/integrations/{IntegrationViewId}/disable",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableMarketplaceIntegration performs POST /{version}/code/marketplace/integrations/{IntegrationViewId}/enable (scope: project).
func (m *CodeModule) EnableMarketplaceIntegration(ctx context.Context, integrationViewId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"IntegrationViewId": integrationViewId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/marketplace/integrations/{IntegrationViewId}/enable",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetMarketplaceFunctionCatalog performs GET /{version}/code/marketplace/integrations/{IntegrationViewId}/functions (scope: project).
func (m *CodeModule) GetMarketplaceFunctionCatalog(ctx context.Context, integrationViewId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"IntegrationViewId": integrationViewId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/marketplace/integrations/{IntegrationViewId}/functions",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetMarketplaceListings performs GET /{version}/code/marketplace/listings (scope: project).
func (m *CodeModule) GetMarketplaceListings(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/marketplace/listings",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetMarketplaceListingFunctionTokens performs GET /{version}/code/marketplace/listings/{ListingViewId}/functions/{FunctionKey}/tokens (scope: project).
func (m *CodeModule) GetMarketplaceListingFunctionTokens(ctx context.Context, listingViewId string, functionKey string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"ListingViewId": listingViewId,
		"FunctionKey":   functionKey,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/code/marketplace/listings/{ListingViewId}/functions/{FunctionKey}/tokens",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
