// Code generated by gen_modules.py. DO NOT EDIT.

package hub

import (
	"context"

	"github.com/norbix-code/sdk-go/v2/norbix/internal/transport"
)

// DatabaseModule groups the database endpoints on the HUB.
type DatabaseModule struct{ t *transport.Transport }

// DisableDatabase performs GET /{version}/database/disable (scope: project).
func (m *DatabaseModule) DisableDatabase(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/disable",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableDatabase performs GET /{version}/database/enable (scope: project).
func (m *DatabaseModule) EnableDatabase(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/enable",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteSchemaTrigger performs DELETE /{version}/database/schemas/triggers/{triggerId} (scope: project).
func (m *DatabaseModule) DeleteSchemaTrigger(ctx context.Context, triggerId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"triggerId": triggerId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers/{triggerId}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisableSchemaTrigger performs PATCH /{version}/database/schemas/triggers/{triggerId}/disable (scope: project).
func (m *DatabaseModule) DisableSchemaTrigger(ctx context.Context, triggerId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"triggerId": triggerId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers/{triggerId}/disable",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableSchemaTrigger performs PATCH /{version}/database/schemas/triggers/{triggerId}/enable (scope: project).
func (m *DatabaseModule) EnableSchemaTrigger(ctx context.Context, triggerId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"triggerId": triggerId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers/{triggerId}/enable",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSchemaTrigger performs GET /{version}/database/schemas/triggers/{id} (scope: project).
func (m *DatabaseModule) GetSchemaTrigger(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSchemaTriggers performs GET /{version}/database/schemas/triggers (scope: project).
func (m *DatabaseModule) GetSchemaTriggers(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveSchemaTrigger performs POST /{version}/database/schemas/triggers (scope: project).
func (m *DatabaseModule) SaveSchemaTrigger(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteDatabaseTaxonomy performs DELETE /{version}/database/taxonomies/{Id} (scope: project).
func (m *DatabaseModule) DeleteDatabaseTaxonomy(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseTaxonomy performs GET /{version}/database/taxonomies/{id} (scope: project).
func (m *DatabaseModule) GetDatabaseTaxonomy(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseTaxonomies performs GET /{version}/database/taxonomies (scope: project).
func (m *DatabaseModule) GetDatabaseTaxonomies(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveDatabaseTaxonomy performs POST /{version}/database/taxonomies (scope: project).
func (m *DatabaseModule) SaveDatabaseTaxonomy(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteDatabaseTaxonomyTerm performs DELETE /{version}/database/taxonomies/{TaxonomyId}/terms/{Id} (scope: project).
func (m *DatabaseModule) DeleteDatabaseTaxonomyTerm(ctx context.Context, taxonomyId string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyId": taxonomyId,
		"Id":         id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyId}/terms/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteManyDatabaseTaxonomyTerms performs DELETE /{version}/database/taxonomies/{TaxonomyId}/terms/many (scope: project).
func (m *DatabaseModule) DeleteManyDatabaseTaxonomyTerms(ctx context.Context, taxonomyId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyId": taxonomyId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyId}/terms/many",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseTaxonomyTerm performs GET /{version}/database/taxonomies/{TaxonomyId}/terms/{Id} (scope: project).
func (m *DatabaseModule) GetDatabaseTaxonomyTerm(ctx context.Context, taxonomyId string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyId": taxonomyId,
		"Id":         id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyId}/terms/{Id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveDatabaseTaxonomyTerm performs POST /{version}/database/taxonomies/{TaxonomyId}/terms (scope: project).
func (m *DatabaseModule) SaveDatabaseTaxonomyTerm(ctx context.Context, taxonomyId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyId": taxonomyId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyId}/terms",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateDatabaseTaxonomyTerm performs PUT /{version}/database/taxonomies/{TaxonomyId}/terms/{Id} (scope: project).
func (m *DatabaseModule) UpdateDatabaseTaxonomyTerm(ctx context.Context, taxonomyId string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyId": taxonomyId,
		"Id":         id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyId}/terms/{Id}",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteDatabaseSchema performs DELETE /{version}/database/schemas/{Id} (scope: project).
func (m *DatabaseModule) DeleteDatabaseSchema(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DiscardDatabaseSchemaDraft performs DELETE /{version}/database/schemas/{Id}/draft (scope: project).
func (m *DatabaseModule) DiscardDatabaseSchemaDraft(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/draft",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchema performs GET /{version}/database/schemas/{id} (scope: project).
func (m *DatabaseModule) GetDatabaseSchema(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchemas performs GET /{version}/database/schemas (scope: project).
func (m *DatabaseModule) GetDatabaseSchemas(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchemaDraft performs GET /{version}/database/schemas/{Id}/draft (scope: project).
func (m *DatabaseModule) GetDatabaseSchemaDraft(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/draft",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchemaVersionDiff performs GET /{version}/database/schemas/{Id}/versions/diff (scope: project).
func (m *DatabaseModule) GetDatabaseSchemaVersionDiff(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/versions/diff",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchemaVersions performs GET /{version}/database/schemas/{Id}/versions (scope: project).
func (m *DatabaseModule) GetDatabaseSchemaVersions(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/versions",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// PublishDatabaseSchema performs POST /{version}/database/schemas/{Id}/publish (scope: project).
func (m *DatabaseModule) PublishDatabaseSchema(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/publish",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RenameDatabaseSchema performs PUT /{version}/database/schemas/{Id}/rename (scope: project).
func (m *DatabaseModule) RenameDatabaseSchema(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/rename",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveDatabaseSchema performs POST /{version}/database/schemas (scope: project).
func (m *DatabaseModule) SaveDatabaseSchema(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateDatabaseSchemaDraft performs PUT /{version}/database/schemas/{Id}/draft (scope: project).
func (m *DatabaseModule) UpdateDatabaseSchemaDraft(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/draft",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateDatabaseSchemaSettings performs PUT /{version}/database/schemas/{Id}/settings (scope: project).
func (m *DatabaseModule) UpdateDatabaseSchemaSettings(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/settings",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteDatabaseIntegration performs DELETE /{version}/database/integrations/{Id} (scope: project).
func (m *DatabaseModule) DeleteDatabaseIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisableDatabaseIntegration performs PUT /{version}/database/integrations/{Id}/disable (scope: project).
func (m *DatabaseModule) DisableDatabaseIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{Id}/disable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableDatabaseIntegration performs PUT /{version}/database/integrations/{Id}/enable (scope: project).
func (m *DatabaseModule) EnableDatabaseIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{Id}/enable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseIntegration performs GET /{version}/database/integrations/{id} (scope: project).
func (m *DatabaseModule) GetDatabaseIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseIntegrations performs GET /{version}/database/integrations (scope: project).
func (m *DatabaseModule) GetDatabaseIntegrations(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveDatabaseIntegration performs POST /{version}/database/integrations (scope: project).
func (m *DatabaseModule) SaveDatabaseIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SetDatabaseIntegrationAsDefault performs PUT /{version}/database/integrations/{Id}/default (scope: project).
func (m *DatabaseModule) SetDatabaseIntegrationAsDefault(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{Id}/default",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteDatabaseAggregate performs DELETE /{version}/database/aggregates/{Id} (scope: project).
func (m *DatabaseModule) DeleteDatabaseAggregate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/aggregates/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseAggregate performs GET /{version}/database/aggregates/{Id} (scope: project).
func (m *DatabaseModule) GetDatabaseAggregate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/aggregates/{Id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseAggregates performs GET /{version}/database/aggregates (scope: project).
func (m *DatabaseModule) GetDatabaseAggregates(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/aggregates",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveDatabaseAggregate performs POST /{version}/database/aggregates (scope: project).
func (m *DatabaseModule) SaveDatabaseAggregate(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/aggregates",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// TestDatabaseAggregate performs POST /{version}/database/aggregates/test (scope: project).
func (m *DatabaseModule) TestDatabaseAggregate(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/aggregates/test",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetAllowedFlexTiers performs GET /{version}/database/integrations/flex-tiers (scope: project).
func (m *DatabaseModule) GetAllowedFlexTiers(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/flex-tiers",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// TestDatabaseIntegration performs POST /{version}/database/integrations/test (scope: project).
func (m *DatabaseModule) TestDatabaseIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/test",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RevealManagedFlexConnectionString performs GET /{version}/database/integrations/{Id}/connection-string (scope: project).
func (m *DatabaseModule) RevealManagedFlexConnectionString(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{Id}/connection-string",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SeedCollectionRecords performs POST /{version}/database/collections/seed (scope: project).
//
// It fills collections with sample records ("mode", "collections", optional "databaseIntegrationId").
func (m *DatabaseModule) SeedCollectionRecords(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/seed",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// FindRecords performs GET /{version}/database/collections/{collectionName} (scope: project).
//
// It lists the records of a collection ("filter" JSON, "sortBy", "sortOrder", "pageSize", "startingAfter", "endingBefore", "contactId", "schemaVersion" go in the query string).
func (m *DatabaseModule) FindRecords(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// InsertRecord performs POST /{version}/database/collections/{collectionName} (scope: project).
//
// It adds one record ("document" is the record as a JSON string).
func (m *DatabaseModule) InsertRecord(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// AggregateRecords performs POST /{version}/database/collections/{collectionName}/aggregate (scope: project).
//
// It runs an aggregation "pipeline" (a JSON string) over the collection.
func (m *DatabaseModule) AggregateRecords(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/aggregate",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ExecuteRecordsAggregate performs POST /{version}/database/collections/{collectionName}/aggregates/{aggregateId}/execute (scope: project).
//
// It runs a saved aggregate against the collection; "tokens" fills its placeholders.
func (m *DatabaseModule) ExecuteRecordsAggregate(ctx context.Context, collectionName string, aggregateId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"aggregateId":    aggregateId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/aggregates/{aggregateId}/execute",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// CountRecords performs GET /{version}/database/collections/{collectionName}/count (scope: project).
//
// It counts the records that match "filter".
func (m *DatabaseModule) CountRecords(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/count",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DistinctRecordValues performs GET /{version}/database/collections/{collectionName}/distinct (scope: project).
//
// It returns the distinct values of "field" among the records that match "filter".
func (m *DatabaseModule) DistinctRecordValues(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/distinct",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetCollectionIndexes performs GET /{version}/database/collections/{collectionName}/indexes (scope: project).
//
// It lists the indexes of the collection.
func (m *DatabaseModule) GetCollectionIndexes(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/indexes",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteManyRecords performs DELETE /{version}/database/collections/{collectionName}/many (scope: project).
//
// It deletes every record that matches "filter" (sent in the query string).
func (m *DatabaseModule) DeleteManyRecords(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/many",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// InsertManyRecords performs POST /{version}/database/collections/{collectionName}/many (scope: project).
//
// It adds several records ("documents" is a JSON array string).
func (m *DatabaseModule) InsertManyRecords(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/many",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateManyRecords performs PUT /{version}/database/collections/{collectionName}/many (scope: project).
//
// It applies "update" to every record that matches "filter".
func (m *DatabaseModule) UpdateManyRecords(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/many",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteRecord performs DELETE /{version}/database/collections/{collectionName}/{id} (scope: project).
//
// It deletes one record.
func (m *DatabaseModule) DeleteRecord(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/{id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// FindOneRecord performs GET /{version}/database/collections/{collectionName}/{id} (scope: project).
//
// It reads one record.
func (m *DatabaseModule) FindOneRecord(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateOneRecord performs PUT /{version}/database/collections/{collectionName}/{id} (scope: project).
//
// It applies "update" (a JSON string) to one record.
func (m *DatabaseModule) UpdateOneRecord(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/{id}",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ReplaceRecord performs PUT /{version}/database/collections/{collectionName}/{id}/replace (scope: project).
//
// It replaces one record with "replacement" (a JSON string).
func (m *DatabaseModule) ReplaceRecord(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/{id}/replace",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ChangeRecordResponsibility performs PUT /{version}/database/collections/{collectionName}/{id}/responsibility (scope: project).
//
// It moves one record to "newResponsibleUserId".
func (m *DatabaseModule) ChangeRecordResponsibility(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/{id}/responsibility",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ApplyDatabaseSchemaBundle performs POST /{version}/database/schemas/apply-bundle (scope: project).
//
// It creates or updates schemas from a bundle ("entities" or "bundleJson", "tier", "translatable", "publish").
func (m *DatabaseModule) ApplyDatabaseSchemaBundle(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/apply-bundle",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateDatabaseSchemaEmbed performs PUT /{version}/database/schemas/{Id}/embed (scope: project).
//
// It stores the schema's "embed" settings (dtos.SchemaEmbedSettingsDto).
func (m *DatabaseModule) UpdateDatabaseSchemaEmbed(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/embed",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchemaListSettings performs GET /{version}/database/schemas/{Id}/list-settings (scope: project).
//
// It reads the schema's record list settings.
func (m *DatabaseModule) GetDatabaseSchemaListSettings(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/list-settings",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateDatabaseSchemaListSettings performs PUT /{version}/database/schemas/{Id}/list-settings (scope: project).
//
// It stores the schema's record list "settings" (dtos.SchemaListSettingsDto).
func (m *DatabaseModule) UpdateDatabaseSchemaListSettings(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/list-settings",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseTaxonomyTree performs GET /{version}/database/taxonomies/tree (scope: project).
//
// It returns every taxonomy as a tree ("includeTerms" adds the terms).
func (m *DatabaseModule) GetDatabaseTaxonomyTree(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/tree",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseMergedTermTree performs GET /{version}/database/taxonomies/{TaxonomyName}/merged-tree (scope: project).
//
// It returns the terms of a taxonomy merged with the terms of the taxonomies it depends on.
func (m *DatabaseModule) GetDatabaseMergedTermTree(ctx context.Context, taxonomyName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyName": taxonomyName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyName}/merged-tree",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseTaxonomyTermTree performs GET /{version}/database/taxonomies/{TaxonomyName}/terms/tree (scope: project).
//
// It returns the terms of a taxonomy as a tree ("rootTermId", "depth").
func (m *DatabaseModule) GetDatabaseTaxonomyTermTree(ctx context.Context, taxonomyName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyName": taxonomyName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyName}/terms/tree",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
