// Code generated by gen_modules.py. DO NOT EDIT.

package hub

import (
	"context"

	"github.com/norbix-code/sdk-go/norbix/internal/transport"
)

// DatabaseModule groups the database endpoints on the HUB.
type DatabaseModule struct{ t *transport.Transport }

// DisableDatabase performs GET /{version}/database/disable (scope: project).
func (m *DatabaseModule) DisableDatabase(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/disable",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableDatabase performs GET /{version}/database/enable (scope: project).
func (m *DatabaseModule) EnableDatabase(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/enable",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteSchemaTrigger performs DELETE /{version}/database/schemas/triggers/{triggerId} (scope: project).
func (m *DatabaseModule) DeleteSchemaTrigger(ctx context.Context, triggerId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"triggerId": triggerId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers/{triggerId}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisableSchemaTrigger performs PATCH /{version}/database/schemas/triggers/{triggerId}/disable (scope: project).
func (m *DatabaseModule) DisableSchemaTrigger(ctx context.Context, triggerId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"triggerId": triggerId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers/{triggerId}/disable",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableSchemaTrigger performs PATCH /{version}/database/schemas/triggers/{triggerId}/enable (scope: project).
func (m *DatabaseModule) EnableSchemaTrigger(ctx context.Context, triggerId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"triggerId": triggerId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers/{triggerId}/enable",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSchemaTrigger performs GET /{version}/database/schemas/triggers/{id} (scope: project).
func (m *DatabaseModule) GetSchemaTrigger(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSchemaTriggers performs GET /{version}/database/schemas/triggers (scope: project).
func (m *DatabaseModule) GetSchemaTriggers(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveSchemaTrigger performs POST /{version}/database/schemas/triggers (scope: project).
func (m *DatabaseModule) SaveSchemaTrigger(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteDatabaseTaxonomy performs DELETE /{version}/database/taxonomies/{Id} (scope: project).
func (m *DatabaseModule) DeleteDatabaseTaxonomy(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseTaxonomy performs GET /{version}/database/taxonomies/{id} (scope: project).
func (m *DatabaseModule) GetDatabaseTaxonomy(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseTaxonomies performs GET /{version}/database/taxonomies (scope: project).
func (m *DatabaseModule) GetDatabaseTaxonomies(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveDatabaseTaxonomy performs POST /{version}/database/taxonomies (scope: project).
func (m *DatabaseModule) SaveDatabaseTaxonomy(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteDatabaseTaxonomyTerm performs DELETE /{version}/database/taxonomies/{TaxonomyId}/terms/{Id} (scope: project).
func (m *DatabaseModule) DeleteDatabaseTaxonomyTerm(ctx context.Context, taxonomyId string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyId": taxonomyId,
		"Id":         id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyId}/terms/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteManyDatabaseTaxonomyTerms performs DELETE /{version}/database/taxonomies/{TaxonomyId}/terms/many (scope: project).
func (m *DatabaseModule) DeleteManyDatabaseTaxonomyTerms(ctx context.Context, taxonomyId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyId": taxonomyId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyId}/terms/many",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseTaxonomyTerm performs GET /{version}/database/taxonomies/{TaxonomyId}/terms/{Id} (scope: project).
func (m *DatabaseModule) GetDatabaseTaxonomyTerm(ctx context.Context, taxonomyId string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyId": taxonomyId,
		"Id":         id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyId}/terms/{Id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveDatabaseTaxonomyTerm performs POST /{version}/database/taxonomies/{TaxonomyId}/terms (scope: project).
func (m *DatabaseModule) SaveDatabaseTaxonomyTerm(ctx context.Context, taxonomyId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyId": taxonomyId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyId}/terms",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateDatabaseTaxonomyTerm performs PUT /{version}/database/taxonomies/{TaxonomyId}/terms/{Id} (scope: project).
func (m *DatabaseModule) UpdateDatabaseTaxonomyTerm(ctx context.Context, taxonomyId string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyId": taxonomyId,
		"Id":         id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyId}/terms/{Id}",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteDatabaseSchema performs DELETE /{version}/database/schemas/{Id} (scope: project).
func (m *DatabaseModule) DeleteDatabaseSchema(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DiscardDatabaseSchemaDraft performs DELETE /{version}/database/schemas/{Id}/draft (scope: project).
func (m *DatabaseModule) DiscardDatabaseSchemaDraft(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/draft",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchema performs GET /{version}/database/schemas/{id} (scope: project).
func (m *DatabaseModule) GetDatabaseSchema(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchemas performs GET /{version}/database/schemas (scope: project).
func (m *DatabaseModule) GetDatabaseSchemas(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchemaDraft performs GET /{version}/database/schemas/{Id}/draft (scope: project).
func (m *DatabaseModule) GetDatabaseSchemaDraft(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/draft",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchemaVersionDiff performs GET /{version}/database/schemas/{Id}/versions/diff (scope: project).
func (m *DatabaseModule) GetDatabaseSchemaVersionDiff(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/versions/diff",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchemaVersions performs GET /{version}/database/schemas/{Id}/versions (scope: project).
func (m *DatabaseModule) GetDatabaseSchemaVersions(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/versions",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// PublishDatabaseSchema performs POST /{version}/database/schemas/{Id}/publish (scope: project).
func (m *DatabaseModule) PublishDatabaseSchema(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/publish",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RenameDatabaseSchema performs PUT /{version}/database/schemas/{Id}/rename (scope: project).
func (m *DatabaseModule) RenameDatabaseSchema(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/rename",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveDatabaseSchema performs POST /{version}/database/schemas (scope: project).
func (m *DatabaseModule) SaveDatabaseSchema(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateDatabaseSchemaDraft performs PUT /{version}/database/schemas/{Id}/draft (scope: project).
func (m *DatabaseModule) UpdateDatabaseSchemaDraft(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/draft",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateDatabaseSchemaSettings performs PUT /{version}/database/schemas/{Id}/settings (scope: project).
func (m *DatabaseModule) UpdateDatabaseSchemaSettings(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/settings",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteDatabaseIntegration performs DELETE /{version}/database/integrations/{Id} (scope: project).
func (m *DatabaseModule) DeleteDatabaseIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisableDatabaseIntegration performs PUT /{version}/database/integrations/{Id}/disable (scope: project).
func (m *DatabaseModule) DisableDatabaseIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{Id}/disable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableDatabaseIntegration performs PUT /{version}/database/integrations/{Id}/enable (scope: project).
func (m *DatabaseModule) EnableDatabaseIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{Id}/enable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseIntegration performs GET /{version}/database/integrations/{id} (scope: project).
func (m *DatabaseModule) GetDatabaseIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseIntegrations performs GET /{version}/database/integrations (scope: project).
func (m *DatabaseModule) GetDatabaseIntegrations(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveDatabaseIntegration performs POST /{version}/database/integrations (scope: project).
func (m *DatabaseModule) SaveDatabaseIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SetDatabaseIntegrationAsDefault performs PUT /{version}/database/integrations/{Id}/default (scope: project).
func (m *DatabaseModule) SetDatabaseIntegrationAsDefault(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{Id}/default",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteDatabaseAggregate performs DELETE /{version}/database/aggregates/{Id} (scope: project).
func (m *DatabaseModule) DeleteDatabaseAggregate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/aggregates/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseAggregate performs GET /{version}/database/aggregates/{Id} (scope: project).
func (m *DatabaseModule) GetDatabaseAggregate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/aggregates/{Id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseAggregates performs GET /{version}/database/aggregates (scope: project).
func (m *DatabaseModule) GetDatabaseAggregates(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/aggregates",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveDatabaseAggregate performs POST /{version}/database/aggregates (scope: project).
func (m *DatabaseModule) SaveDatabaseAggregate(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/aggregates",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// TestDatabaseAggregate performs POST /{version}/database/aggregates/test (scope: project).
func (m *DatabaseModule) TestDatabaseAggregate(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/aggregates/test",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetAllowedFlexTiers performs GET /{version}/database/integrations/flex-tiers (scope: project).
func (m *DatabaseModule) GetAllowedFlexTiers(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/flex-tiers",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// TestDatabaseIntegration performs POST /{version}/database/integrations/test (scope: project).
func (m *DatabaseModule) TestDatabaseIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/test",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RevealManagedFlexConnectionString performs GET /{version}/database/integrations/{Id}/connection-string (scope: project).
func (m *DatabaseModule) RevealManagedFlexConnectionString(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{Id}/connection-string",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
