// Code generated by gen_modules.py. DO NOT EDIT.

package hub

import (
	"context"

	"github.com/norbix-code/sdk-go/v2/norbix/internal/transport"
)

// DatabaseModule groups the database endpoints on the HUB.
type DatabaseModule struct{ t *transport.Transport }

// DisableDatabase performs PUT /{version}/database/disable (scope: project).
func (m *DatabaseModule) DisableDatabase(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/disable",
		Method:     "PUT",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableDatabase performs PUT /{version}/database/enable (scope: project).
func (m *DatabaseModule) EnableDatabase(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/enable",
		Method:     "PUT",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteSchemaTrigger performs DELETE /{version}/database/schemas/triggers/{triggerId} (scope: project).
//
// It acts on the copy of the trigger in the request environment (norbix-env, PROD when absent); no
// copy there answers CM-ERRORS-TRIGGERS-002.
func (m *DatabaseModule) DeleteSchemaTrigger(ctx context.Context, triggerId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"triggerId": triggerId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers/{triggerId}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisableSchemaTrigger performs PATCH /{version}/database/schemas/triggers/{triggerId}/disable (scope: project).
//
// It acts on the copy of the trigger in the request environment (norbix-env, PROD when absent); no
// copy there answers CM-ERRORS-TRIGGERS-002.
func (m *DatabaseModule) DisableSchemaTrigger(ctx context.Context, triggerId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"triggerId": triggerId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers/{triggerId}/disable",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableSchemaTrigger performs PATCH /{version}/database/schemas/triggers/{triggerId}/enable (scope: project).
//
// It acts on the copy of the trigger in the request environment (norbix-env, PROD when absent); no
// copy there answers CM-ERRORS-TRIGGERS-002.
func (m *DatabaseModule) EnableSchemaTrigger(ctx context.Context, triggerId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"triggerId": triggerId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers/{triggerId}/enable",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSchemaTrigger performs GET /{version}/database/schemas/triggers/{id} (scope: project).
//
// It reads one schema trigger (dtos.SchemaTriggerDto): SchemaId is the owning schema (sch_...), Env
// its environment.
func (m *DatabaseModule) GetSchemaTrigger(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSchemaTriggers performs GET /{version}/database/schemas/triggers (scope: project).
//
// It lists the schema triggers of the request environment only (norbix-env, PROD when absent); each
// row carries Env.
func (m *DatabaseModule) GetSchemaTriggers(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveSchemaTrigger performs POST /{version}/database/schemas/triggers (scope: project).
//
// It creates or updates a schema trigger. An existing trigger id under another schema is refused with
// CM-ERRORS-TRIGGERS-002.
func (m *DatabaseModule) SaveSchemaTrigger(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/triggers",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteDatabaseTaxonomy performs DELETE /{version}/database/taxonomies/{Id} (scope: project).
func (m *DatabaseModule) DeleteDatabaseTaxonomy(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseTaxonomy performs GET /{version}/database/taxonomies/{id} (scope: project).
func (m *DatabaseModule) GetDatabaseTaxonomy(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseTaxonomies performs GET /{version}/database/taxonomies (scope: project).
//
// It lists the taxonomies; each row (dtos.TaxonomyListProjection) carries DependencyRefs, one {Id,
// Name} per dependency in the order of Dependencies (Name is empty when the dependency no longer
// exists).
func (m *DatabaseModule) GetDatabaseTaxonomies(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveDatabaseTaxonomy performs POST /{version}/database/taxonomies (scope: project).
//
// It creates a taxonomy (database:create on all), or updates one when "viewId" names an existing
// taxonomy (database:update on database:taxonomy:<viewId>).
func (m *DatabaseModule) SaveDatabaseTaxonomy(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteDatabaseTaxonomyTerm performs DELETE /{version}/database/taxonomies/{TaxonomyId}/terms/{Id} (scope: project).
func (m *DatabaseModule) DeleteDatabaseTaxonomyTerm(ctx context.Context, taxonomyId string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyId": taxonomyId,
		"Id":         id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyId}/terms/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteManyDatabaseTaxonomyTerms performs DELETE /{version}/database/taxonomies/{TaxonomyId}/terms/many (scope: project).
func (m *DatabaseModule) DeleteManyDatabaseTaxonomyTerms(ctx context.Context, taxonomyId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyId": taxonomyId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyId}/terms/many",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseTaxonomyTerm performs GET /{version}/database/taxonomies/{TaxonomyId}/terms/{Id} (scope: project).
func (m *DatabaseModule) GetDatabaseTaxonomyTerm(ctx context.Context, taxonomyId string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyId": taxonomyId,
		"Id":         id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyId}/terms/{Id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveDatabaseTaxonomyTerm performs POST /{version}/database/taxonomies/{TaxonomyId}/terms (scope: project).
func (m *DatabaseModule) SaveDatabaseTaxonomyTerm(ctx context.Context, taxonomyId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyId": taxonomyId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyId}/terms",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateDatabaseTaxonomyTerm performs PUT /{version}/database/taxonomies/{TaxonomyId}/terms/{Id} (scope: project).
func (m *DatabaseModule) UpdateDatabaseTaxonomyTerm(ctx context.Context, taxonomyId string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyId": taxonomyId,
		"Id":         id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyId}/terms/{Id}",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteDatabaseSchema performs DELETE /{version}/database/schemas/{Id} (scope: project).
//
// It deletes a schema. A schema a saved aggregate still uses, as its start or as a joined collection,
// is refused with CM-ERRORS-SCHEMA-018 (context: BlockerAggregateIds, BlockerAggregateNames).
func (m *DatabaseModule) DeleteDatabaseSchema(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DiscardDatabaseSchemaDraft performs DELETE /{version}/database/schemas/{Id}/draft (scope: project).
func (m *DatabaseModule) DiscardDatabaseSchemaDraft(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/draft",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchema performs GET /{version}/database/schemas/{id} (scope: project).
func (m *DatabaseModule) GetDatabaseSchema(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchemas performs GET /{version}/database/schemas (scope: project).
func (m *DatabaseModule) GetDatabaseSchemas(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchemaDraft performs GET /{version}/database/schemas/{Id}/draft (scope: project).
func (m *DatabaseModule) GetDatabaseSchemaDraft(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/draft",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchemaVersionDiff performs GET /{version}/database/schemas/{Id}/versions/diff (scope: project).
func (m *DatabaseModule) GetDatabaseSchemaVersionDiff(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/versions/diff",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchemaVersions performs GET /{version}/database/schemas/{Id}/versions (scope: project).
func (m *DatabaseModule) GetDatabaseSchemaVersions(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/versions",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// PublishDatabaseSchema performs POST /{version}/database/schemas/{Id}/publish (scope: project).
func (m *DatabaseModule) PublishDatabaseSchema(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/publish",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RenameDatabaseSchema performs PUT /{version}/database/schemas/{Id}/rename (scope: project).
//
// It renames a schema ("title"). A name another schema in the same environment already uses is refused
// with CM-ERRORS-SCHEMA-002.
func (m *DatabaseModule) RenameDatabaseSchema(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/rename",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveDatabaseSchema performs POST /{version}/database/schemas (scope: project).
func (m *DatabaseModule) SaveDatabaseSchema(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateDatabaseSchemaDraft performs PUT /{version}/database/schemas/{Id}/draft (scope: project).
func (m *DatabaseModule) UpdateDatabaseSchemaDraft(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/draft",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateDatabaseSchemaSettings performs PUT /{version}/database/schemas/{Id}/settings (scope: project).
func (m *DatabaseModule) UpdateDatabaseSchemaSettings(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/settings",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteDatabaseIntegration performs DELETE /{version}/database/integrations/{Id} (scope: project).
func (m *DatabaseModule) DeleteDatabaseIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisableDatabaseIntegration performs PUT /{version}/database/integrations/{Id}/disable (scope: project).
func (m *DatabaseModule) DisableDatabaseIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{Id}/disable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableDatabaseIntegration performs PUT /{version}/database/integrations/{Id}/enable (scope: project).
func (m *DatabaseModule) EnableDatabaseIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{Id}/enable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseIntegration performs GET /{version}/database/integrations/{id} (scope: project).
func (m *DatabaseModule) GetDatabaseIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseIntegrations performs GET /{version}/database/integrations (scope: project).
func (m *DatabaseModule) GetDatabaseIntegrations(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveDatabaseIntegration performs POST /{version}/database/integrations (scope: project).
func (m *DatabaseModule) SaveDatabaseIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SetDatabaseIntegrationAsDefault performs PUT /{version}/database/integrations/{Id}/default (scope: project).
func (m *DatabaseModule) SetDatabaseIntegrationAsDefault(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{Id}/default",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteDatabaseAggregate performs DELETE /{version}/database/aggregates/{Id} (scope: project).
func (m *DatabaseModule) DeleteDatabaseAggregate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/aggregates/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseAggregate performs GET /{version}/database/aggregates/{Id} (scope: project).
func (m *DatabaseModule) GetDatabaseAggregate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/aggregates/{Id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseAggregates performs GET /{version}/database/aggregates (scope: project).
//
// It lists the saved aggregates; each (dtos.MongoDbAggregateDto) names the collections it joins in
// JoinedCollections.
func (m *DatabaseModule) GetDatabaseAggregates(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/aggregates",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveDatabaseAggregate performs POST /{version}/database/aggregates (scope: project).
func (m *DatabaseModule) SaveDatabaseAggregate(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/aggregates",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// TestDatabaseAggregate performs POST /{version}/database/aggregates/test (scope: project).
//
// It runs a pipeline without saving it. It needs database:create or database:update on
// database:aggregate:<schemaId>, plus database:read.
func (m *DatabaseModule) TestDatabaseAggregate(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/aggregates/test",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetAllowedFlexTiers performs GET /{version}/database/integrations/flex-tiers (scope: project).
func (m *DatabaseModule) GetAllowedFlexTiers(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/flex-tiers",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// TestDatabaseIntegration performs POST /{version}/database/integrations/test (scope: project).
func (m *DatabaseModule) TestDatabaseIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/test",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RevealManagedFlexConnectionString performs GET /{version}/database/integrations/{Id}/connection-string (scope: project).
func (m *DatabaseModule) RevealManagedFlexConnectionString(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/integrations/{Id}/connection-string",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SeedCollectionRecords performs POST /{version}/database/collections/seed (scope: project).
//
// It fills collections with sample records ("mode", "collections", optional "databaseIntegrationId").
func (m *DatabaseModule) SeedCollectionRecords(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/seed",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// FindRecords performs GET /{version}/database/collections/{collectionName} (scope: project).
//
// It lists the records of a collection ("filter" JSON, "sortBy", "sortOrder", "pageSize", "startingAfter", "endingBefore", "contactId", "schemaVersion" go in the query string).
//
// "expandReferences": true (query) returns every reference field (user, role, term, record, file — at
// any nesting depth) as {"id": "...", "display": ...} — an array of them when the field is multiple —
// where "display" is the target's property named by the schema's displayField; a target that no
// longer exists gives "display": null, the id is always kept. Decode such a value into
// ExpandedReference. The caller must hold read on this collection AND on every source the published
// schema links to; one missing source refuses the whole read with CM-ERRORS-DATABASE-056 (context:
// SourceKind, Source, Fields, MissingPermissions) before any record is read. Off (default): the
// records exactly as stored, no source check.
func (m *DatabaseModule) FindRecords(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// InsertRecord performs POST /{version}/database/collections/{collectionName} (scope: project).
//
// It adds one record ("document" is the record as a JSON string).
//
// A body that is not a JSON object is refused with CM-ERRORS-DATABASE-036 "Invalid record document".
func (m *DatabaseModule) InsertRecord(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// AggregateRecords performs POST /{version}/database/collections/{collectionName}/aggregate (scope: project).
//
// It runs an aggregation "pipeline" (a JSON string) over the collection.
func (m *DatabaseModule) AggregateRecords(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/aggregate",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ExecuteRecordsAggregate performs POST /{version}/database/collections/{collectionName}/aggregates/{aggregateId}/execute (scope: project).
//
// It runs a saved aggregate against the collection; "tokens" fills its placeholders.
func (m *DatabaseModule) ExecuteRecordsAggregate(ctx context.Context, collectionName string, aggregateId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"aggregateId":    aggregateId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/aggregates/{aggregateId}/execute",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// CountRecords performs GET /{version}/database/collections/{collectionName}/count (scope: project).
//
// It counts the records that match "filter".
func (m *DatabaseModule) CountRecords(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/count",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DistinctRecordValues performs GET /{version}/database/collections/{collectionName}/distinct (scope: project).
//
// It returns the distinct values of "field" among the records that match "filter".
func (m *DatabaseModule) DistinctRecordValues(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/distinct",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetCollectionIndexes performs GET /{version}/database/collections/{collectionName}/indexes (scope: project).
//
// It lists the indexes of the collection.
func (m *DatabaseModule) GetCollectionIndexes(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/indexes",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteManyRecords performs DELETE /{version}/database/collections/{collectionName}/many (scope: project).
//
// It deletes every record that matches "filter" (sent in the query string, with "allRecords").
//
// An empty filter ("{}") touches every record, so the gateway refuses it with CM-ERRORS-DATABASE-037
// unless "allRecords" is true.
//
// A caller with only own-record rights (createAsUser / updateOwn / deleteOwn) may call it; it then
// touches only that caller's records.
func (m *DatabaseModule) DeleteManyRecords(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/many",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// InsertManyRecords performs POST /{version}/database/collections/{collectionName}/many (scope: project).
//
// It adds several records ("documents" is a JSON array string).
//
// A caller with only own-record rights (createAsUser / updateOwn / deleteOwn) may call it; it then
// touches only that caller's records.
//
// An item that is not a JSON object is refused with CM-ERRORS-DATABASE-036 "Invalid record document"
// (its "Index" in the error context).
func (m *DatabaseModule) InsertManyRecords(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/many",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateManyRecords performs PUT /{version}/database/collections/{collectionName}/many (scope: project).
//
// It applies "update" to every record that matches "filter" (a missing filter counts as "{}").
//
// "arrayFilters" (optional, a JSON string): a MongoDB arrayFilters ARRAY, one filter document per
// $[name] identifier used in an "update" path — e.g. "update": {"lines.$[line].qty":3} with
// "arrayFilters": [{"line.sku":"A-1"}] — to change one element of a nested array in place.
//
// "update" is the bare field document (e.g. {"price":12}); the gateway applies it with $set. A body
// with $ operators ($set, $inc, ...) is refused with CM-ERRORS-DATABASE-035.
//
// An empty filter ("{}") touches every record, so the gateway refuses it with CM-ERRORS-DATABASE-037
// unless "allRecords" is true.
//
// A caller with only own-record rights (createAsUser / updateOwn / deleteOwn) may call it; it then
// touches only that caller's records.
//
// Soft-deleted records are skipped.
func (m *DatabaseModule) UpdateManyRecords(ctx context.Context, collectionName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/many",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteRecord performs DELETE /{version}/database/collections/{collectionName}/{id} (scope: project).
//
// It deletes one record.
func (m *DatabaseModule) DeleteRecord(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/{id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// FindOneRecord performs GET /{version}/database/collections/{collectionName}/{id} (scope: project).
//
// It reads one record.
//
// "expandReferences": true (query) returns every reference field (user, role, term, record, file — at
// any nesting depth) as {"id": "...", "display": ...} — an array of them when the field is multiple —
// where "display" is the target's property named by the schema's displayField; a target that no
// longer exists gives "display": null, the id is always kept. Decode such a value into
// ExpandedReference. The caller must hold read on this collection AND on every source the published
// schema links to; one missing source refuses the whole read with CM-ERRORS-DATABASE-056 (context:
// SourceKind, Source, Fields, MissingPermissions) before any record is read. Off (default): the
// records exactly as stored, no source check.
func (m *DatabaseModule) FindOneRecord(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateOneRecord performs PUT /{version}/database/collections/{collectionName}/{id} (scope: project).
//
// It applies "update" (a JSON string) to one record.
//
// "arrayFilters" (optional, a JSON string): a MongoDB arrayFilters ARRAY, one filter document per
// $[name] identifier used in an "update" path — e.g. "update": {"lines.$[line].qty":3} with
// "arrayFilters": [{"line.sku":"A-1"}] — to change one element of a nested array in place.
//
// "update" is the bare field document (e.g. {"price":12}); the gateway applies it with $set. A body
// with $ operators ($set, $inc, ...) is refused with CM-ERRORS-DATABASE-035.
//
// Soft-deleted records are not matched: such a record is "not found".
func (m *DatabaseModule) UpdateOneRecord(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/{id}",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ReplaceRecord performs PUT /{version}/database/collections/{collectionName}/{id}/replace (scope: project).
//
// It replaces one record with "replacement" (a JSON string).
//
// A body that is not a JSON object is refused with CM-ERRORS-DATABASE-036 "Invalid record document".
//
// Soft-deleted records are not matched: such a record is "not found".
func (m *DatabaseModule) ReplaceRecord(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/{id}/replace",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ChangeRecordResponsibility performs PUT /{version}/database/collections/{collectionName}/{id}/responsibility (scope: project).
//
// It moves one record to "newResponsibleUserId".
//
// A new owner who is not a user of the project in the request environment is refused with
// CM-ERRORS-MEMBERSHIP-USERS-012.
//
// Soft-deleted records are not matched: such a record is "not found".
func (m *DatabaseModule) ChangeRecordResponsibility(ctx context.Context, collectionName string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"collectionName": collectionName,
		"id":             id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/collections/{collectionName}/{id}/responsibility",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ApplyDatabaseSchemaBundle performs POST /{version}/database/schemas/apply-bundle (scope: project).
//
// It creates or updates schemas from a bundle ("entities" or "bundleJson", "tier", "translatable", "publish").
func (m *DatabaseModule) ApplyDatabaseSchemaBundle(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/apply-bundle",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateDatabaseSchemaEmbed performs PUT /{version}/database/schemas/{Id}/embed (scope: project).
//
// It stores the schema's "embed" settings (dtos.SchemaEmbedSettingsDto).
func (m *DatabaseModule) UpdateDatabaseSchemaEmbed(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/embed",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchemaIndexStatus performs GET /{version}/database/schemas/{Id}/index-status (scope: project).
//
// It reads the last schema-index run of the collection in the request's
// environment: which indexes Norbix wanted, created, dropped or could not
// create, per database (state building | ready | refused | partial).
func (m *DatabaseModule) GetDatabaseSchemaIndexStatus(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/index-status",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseSchemaListSettings performs GET /{version}/database/schemas/{Id}/list-settings (scope: project).
//
// It reads the schema's record list settings.
func (m *DatabaseModule) GetDatabaseSchemaListSettings(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/list-settings",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateDatabaseSchemaListSettings performs PUT /{version}/database/schemas/{Id}/list-settings (scope: project).
//
// It stores the schema's record list "settings" (dtos.SchemaListSettingsDto).
func (m *DatabaseModule) UpdateDatabaseSchemaListSettings(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/schemas/{Id}/list-settings",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseTaxonomyTree performs GET /{version}/database/taxonomies/tree (scope: project).
//
// It returns every taxonomy as a tree ("includeTerms" adds the terms).
//
// With "includeTerms" the call fails when the term read fails (it no longer returns the taxonomies
// without terms). More than 5000 terms answers CM-ERRORS-TAXONOMIES-011; read a sub-tree instead
// (rootTermId, depth).
func (m *DatabaseModule) GetDatabaseTaxonomyTree(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/tree",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseMergedTermTree performs GET /{version}/database/taxonomies/{TaxonomyName}/merged-tree (scope: project).
//
// It returns the terms of a taxonomy merged with the terms of the taxonomies it depends on.
//
// It needs database:read on database:term:<id> of the taxonomy and of every nested taxonomy. An
// unknown taxonomy name answers CM-ERRORS-TAXONOMIES-010. More than 5000 terms answers
// CM-ERRORS-TAXONOMIES-011; read a sub-tree instead (rootTermId, depth).
func (m *DatabaseModule) GetDatabaseMergedTermTree(ctx context.Context, taxonomyName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyName": taxonomyName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyName}/merged-tree",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetDatabaseTaxonomyTermTree performs GET /{version}/database/taxonomies/{TaxonomyName}/terms/tree (scope: project).
//
// It returns the terms of a taxonomy as a tree ("rootTermId", "depth").
//
// It needs database:read on database:term:<taxonomy id>. An unknown taxonomy name answers
// CM-ERRORS-TAXONOMIES-010; a name over 40 characters answers CM-ERRORS-TAXONOMIES-005. More than 5000
// terms answers CM-ERRORS-TAXONOMIES-011; read a sub-tree instead (rootTermId, depth).
func (m *DatabaseModule) GetDatabaseTaxonomyTermTree(ctx context.Context, taxonomyName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"TaxonomyName": taxonomyName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/database/taxonomies/{TaxonomyName}/terms/tree",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
