// Code generated by gen_modules.py. DO NOT EDIT.

package hub

import (
	"context"

	"github.com/norbix-code/sdk-go/norbix/internal/transport"
)

// EmailModule groups the email endpoints on the HUB.
type EmailModule struct{ t *transport.Transport }

// OneClickUnsubscribe performs POST /{version}/email/one-click-unsubscribe (scope: project).
func (m *EmailModule) OneClickUnsubscribe(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/email/one-click-unsubscribe",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
