// Code generated by gen_modules.py. DO NOT EDIT.

package hub

import (
	"context"

	"github.com/norbix-code/sdk-go/norbix/internal/transport"
)

// EnvironmentsModule groups the environments endpoints on the HUB.
type EnvironmentsModule struct{ t *transport.Transport }

// List performs GET /{version}/account/projects/environments (scope: project).
func (m *EnvironmentsModule) List(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/environments",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// Create performs POST /{version}/account/projects/environments (scope: project).
func (m *EnvironmentsModule) Create(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/environments",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// Delete performs DELETE /{version}/account/projects/environments/{environmentName} (scope: project).
func (m *EnvironmentsModule) Delete(ctx context.Context, environmentName string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"environmentName": environmentName,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/environments/{environmentName}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
