// Code generated by gen_modules.py. DO NOT EDIT.

package hub

import (
	"context"

	"github.com/norbix-code/sdk-go/norbix/internal/transport"
)

// FilesModule groups the files endpoints on the HUB.
type FilesModule struct{ t *transport.Transport }

// DisableFiles performs GET /{version}/files/disable (scope: project).
func (m *FilesModule) DisableFiles(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/disable",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableFiles performs GET /{version}/files/enable (scope: project).
func (m *FilesModule) EnableFiles(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/enable",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetFolderFiles performs GET /{version}/files/folder (scope: project).
func (m *FilesModule) GetFolderFiles(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/folder",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetFile performs GET /{version}/files/item (scope: project).
func (m *FilesModule) GetFile(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/item",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteFilesTrigger performs DELETE /{version}/files/triggers/{triggerId} (scope: project).
func (m *FilesModule) DeleteFilesTrigger(ctx context.Context, triggerId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"triggerId": triggerId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/triggers/{triggerId}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisableFilesTrigger performs PATCH /{version}/files/triggers/{triggerId}/disable (scope: project).
func (m *FilesModule) DisableFilesTrigger(ctx context.Context, triggerId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"triggerId": triggerId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/triggers/{triggerId}/disable",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableFilesTrigger performs PATCH /{version}/files/triggers/{triggerId}/enable (scope: project).
func (m *FilesModule) EnableFilesTrigger(ctx context.Context, triggerId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"triggerId": triggerId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/triggers/{triggerId}/enable",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetFilesTrigger performs GET /{version}/files/triggers/{id} (scope: project).
func (m *FilesModule) GetFilesTrigger(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/triggers/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetFilesTriggers performs GET /{version}/files/triggers (scope: project).
func (m *FilesModule) GetFilesTriggers(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/triggers",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveFilesTrigger performs POST /{version}/files/triggers (scope: project).
func (m *FilesModule) SaveFilesTrigger(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/triggers",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteFilesIntegration performs DELETE /{version}/files/integrations/{Id} (scope: project).
func (m *FilesModule) DeleteFilesIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/integrations/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisableFilesIntegration performs PUT /{version}/files/integrations/{Id}/disable (scope: project).
func (m *FilesModule) DisableFilesIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/integrations/{Id}/disable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableFilesIntegration performs PUT /{version}/files/integrations/{Id}/enable (scope: project).
func (m *FilesModule) EnableFilesIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/integrations/{Id}/enable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetFilesIntegration performs GET /{version}/files/integrations/{id} (scope: project).
func (m *FilesModule) GetFilesIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/integrations/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetFilesIntegrations performs GET /{version}/files/integrations (scope: project).
func (m *FilesModule) GetFilesIntegrations(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/integrations",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveFilesIntegration performs POST /{version}/files/integrations (scope: project).
func (m *FilesModule) SaveFilesIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/integrations",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// TestFilesIntegration performs POST /{version}/files/integrations/test (scope: project).
func (m *FilesModule) TestFilesIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/integrations/test",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SetFilesIntegrationAsDefault performs PUT /{version}/files/integrations/{Id}/default (scope: project).
func (m *FilesModule) SetFilesIntegrationAsDefault(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/files/integrations/{Id}/default",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
