// Code generated by gen_modules.py. DO NOT EDIT.

package hub

import (
	"context"

	"github.com/norbix-code/sdk-go/norbix/internal/transport"
)

// InternalModule groups the internal endpoints on the HUB.
type InternalModule struct{ t *transport.Transport }

// InternalsTypeGen performs GET /internal/_typegen (scope: project).
func (m *InternalModule) InternalsTypeGen(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/internal/_typegen",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
