// Code generated by gen_modules.py. DO NOT EDIT.

// Package hub exposes the Norbix HUB endpoint modules.
package hub

import "github.com/norbix-code/sdk-go/norbix/internal/transport"

// Namespace bundles every HUB module.
type Namespace struct {
	Account       *AccountModule
	Ai            *AiModule
	Code          *CodeModule
	Database      *DatabaseModule
	Echo          *EchoModule
	Email         *EmailModule
	Environments  *EnvironmentsModule
	Files         *FilesModule
	Internal      *InternalModule
	Logs          *LogsModule
	Membership    *MembershipModule
	Notifications *NotificationsModule
	Payments      *PaymentsModule
	Regions       *RegionsModule
	Resources     *ResourcesModule
	Scheduler     *SchedulerModule
	Webhooks      *WebhooksModule
}

// NewNamespace wires every module to the shared transport.
func NewNamespace(t *transport.Transport) *Namespace {
	return &Namespace{
		Account:       &AccountModule{t: t},
		Ai:            &AiModule{t: t},
		Code:          &CodeModule{t: t},
		Database:      &DatabaseModule{t: t},
		Echo:          &EchoModule{t: t},
		Email:         &EmailModule{t: t},
		Environments:  &EnvironmentsModule{t: t},
		Files:         &FilesModule{t: t},
		Internal:      &InternalModule{t: t},
		Logs:          &LogsModule{t: t},
		Membership:    &MembershipModule{t: t},
		Notifications: &NotificationsModule{t: t},
		Payments:      &PaymentsModule{t: t},
		Regions:       &RegionsModule{t: t},
		Resources:     &ResourcesModule{t: t},
		Scheduler:     &SchedulerModule{t: t},
		Webhooks:      &WebhooksModule{t: t},
	}
}
