// Code generated by gen_modules.py. DO NOT EDIT.

package hub

import (
	"context"

	"github.com/norbix-code/sdk-go/norbix/internal/transport"
)

// NotificationsModule groups the notifications endpoints on the HUB.
type NotificationsModule struct{ t *transport.Transport }

// GetUserNotificationPreferences performs GET /{version}/notifications/user/preferences (scope: project).
func (m *NotificationsModule) GetUserNotificationPreferences(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/user/preferences",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateUserNotificationsPreferences performs PUT /{version}/notifications/user/preferences (scope: project).
func (m *NotificationsModule) UpdateUserNotificationsPreferences(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/user/preferences",
		Method:     "PUT",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisableEmail performs GET /{version}/notifications/email/disable (scope: project).
func (m *NotificationsModule) DisableEmail(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/disable",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableEmail performs GET /{version}/notifications/email/enable (scope: project).
func (m *NotificationsModule) EnableEmail(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/enable",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// AttachFileToTemplate performs POST /{version}/notifications/email/templates/attachments (scope: project).
func (m *NotificationsModule) AttachFileToTemplate(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/templates/attachments",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// CreateEmailTemplate performs POST /{version}/notifications/email/templates (scope: project).
func (m *NotificationsModule) CreateEmailTemplate(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/templates",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteEmailTemplate performs DELETE /{version}/notifications/email/templates/{Id} (scope: project).
func (m *NotificationsModule) DeleteEmailTemplate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/templates/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailTemplate performs GET /{version}/notifications/email/templates/{id} (scope: project).
func (m *NotificationsModule) GetEmailTemplate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/templates/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailTemplates performs GET /{version}/notifications/email/templates (scope: project).
func (m *NotificationsModule) GetEmailTemplates(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/templates",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetMjml performs POST /{version}/notifications/email/templates/mjml (scope: project).
func (m *NotificationsModule) GetMjml(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/templates/mjml",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSystemEmailTemplate performs GET /{version}/notifications/email/system-templates/{id} (scope: project).
func (m *NotificationsModule) GetSystemEmailTemplate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/system-templates/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSystemEmailTemplates performs GET /{version}/notifications/email/system-templates (scope: project).
func (m *NotificationsModule) GetSystemEmailTemplates(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/system-templates",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailTemplateAvailableTokens performs GET /{version}/notifications/email/templates/{id}/tokens (scope: project).
func (m *NotificationsModule) GetEmailTemplateAvailableTokens(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/templates/{id}/tokens",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateEmailTemplate performs PUT /{version}/notifications/email/templates (scope: project).
func (m *NotificationsModule) UpdateEmailTemplate(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/templates",
		Method:     "PUT",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteEmailSignature performs DELETE /{version}/notifications/email/signatures/{id} (scope: project).
func (m *NotificationsModule) DeleteEmailSignature(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/signatures/{id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailSignature performs GET /{version}/notifications/email/signatures/{id} (scope: project).
func (m *NotificationsModule) GetEmailSignature(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/signatures/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailSignatures performs GET /{version}/notifications/email/signatures (scope: project).
func (m *NotificationsModule) GetEmailSignatures(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/signatures",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveEmailSignature performs POST /{version}/notifications/email/signatures (scope: project).
func (m *NotificationsModule) SaveEmailSignature(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/signatures",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailSettings performs GET /{version}/notifications/email/settings (scope: project).
func (m *NotificationsModule) GetEmailSettings(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/settings",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ConfirmEmailIntegrationHumanDelivery performs POST /{version}/notifications/email/integrations/confirm-human-delivery (scope: project).
func (m *NotificationsModule) ConfirmEmailIntegrationHumanDelivery(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/integrations/confirm-human-delivery",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteEmailIntegration performs DELETE /{version}/notifications/email/integrations/{Id} (scope: project).
func (m *NotificationsModule) DeleteEmailIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/integrations/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisableEmailIntegration performs PUT /{version}/notifications/email/integrations/{Id}/disable (scope: project).
func (m *NotificationsModule) DisableEmailIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/integrations/{Id}/disable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableEmailIntegration performs PUT /{version}/notifications/email/integrations/{Id}/enable (scope: project).
func (m *NotificationsModule) EnableEmailIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/integrations/{Id}/enable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailIntegration performs GET /{version}/notifications/email/integrations/{id} (scope: project).
func (m *NotificationsModule) GetEmailIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/integrations/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailIntegrations performs GET /{version}/notifications/email/integrations (scope: project).
func (m *NotificationsModule) GetEmailIntegrations(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/integrations",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveEmailIntegration performs POST /{version}/notifications/email/integrations (scope: project).
func (m *NotificationsModule) SaveEmailIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/integrations",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SetEmailsIntegrationAsDefault performs PUT /{version}/notifications/email/integrations/{Id}/default (scope: project).
func (m *NotificationsModule) SetEmailsIntegrationAsDefault(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/integrations/{Id}/default",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// TestEmailIntegration performs POST /{version}/notifications/email/integrations/test (scope: project).
func (m *NotificationsModule) TestEmailIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/integrations/test",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ArchiveEmailTemplate performs PUT /{version}/notifications/email/templates/{Id}/archive (scope: project).
func (m *NotificationsModule) ArchiveEmailTemplate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/templates/{Id}/archive",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// CloneEmailTemplate performs POST /{version}/notifications/email/templates/{Id}/clone (scope: project).
func (m *NotificationsModule) CloneEmailTemplate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/templates/{Id}/clone",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UnArchiveEmailTemplate performs PUT /{version}/notifications/email/templates/{Id}/unarchive (scope: project).
func (m *NotificationsModule) UnArchiveEmailTemplate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/templates/{Id}/unarchive",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteEmailFooter performs DELETE /{version}/notifications/email/footers/{id} (scope: project).
func (m *NotificationsModule) DeleteEmailFooter(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/footers/{id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailFooter performs GET /{version}/notifications/email/footers/{id} (scope: project).
func (m *NotificationsModule) GetEmailFooter(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/footers/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailFooters performs GET /{version}/notifications/email/footers (scope: project).
func (m *NotificationsModule) GetEmailFooters(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/footers",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveEmailFooter performs POST /{version}/notifications/email/footers (scope: project).
func (m *NotificationsModule) SaveEmailFooter(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/footers",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// CreateEmailCampaign performs POST /{version}/notifications/email/campaigns (scope: project).
func (m *NotificationsModule) CreateEmailCampaign(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/campaigns",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteEmailCampaign performs DELETE /{version}/notifications/email/campaigns/{Id} (scope: project).
func (m *NotificationsModule) DeleteEmailCampaign(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/campaigns/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailCampaign performs GET /{version}/notifications/email/campaigns/{id} (scope: project).
func (m *NotificationsModule) GetEmailCampaign(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/campaigns/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailCampaigns performs GET /{version}/notifications/email/campaigns (scope: project).
func (m *NotificationsModule) GetEmailCampaigns(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/campaigns",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailCampaignBatches performs GET /{version}/notifications/email/campaigns/{id}/batches (scope: project).
func (m *NotificationsModule) GetEmailCampaignBatches(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/campaigns/{id}/batches",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailCampaignBatchNotification performs GET /{version}/notifications/email/campaigns/{id}/batches/{batchId}/{notificationId} (scope: project).
func (m *NotificationsModule) GetEmailCampaignBatchNotification(ctx context.Context, id string, batchId string, notificationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id":             id,
		"batchId":        batchId,
		"notificationId": notificationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/campaigns/{id}/batches/{batchId}/{notificationId}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailCampaignBatchNotifications performs GET /{version}/notifications/email/campaigns/{id}/batches/{batchId} (scope: project).
func (m *NotificationsModule) GetEmailCampaignBatchNotifications(ctx context.Context, id string, batchId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id":      id,
		"batchId": batchId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/campaigns/{id}/batches/{batchId}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailCampaignStatistics performs GET /{version}/notifications/email/campaigns/{id}/stats (scope: project).
func (m *NotificationsModule) GetEmailCampaignStatistics(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/campaigns/{id}/stats",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// PreviewEmailNotification performs GET /{version}/notifications/email/preview (scope: project).
func (m *NotificationsModule) PreviewEmailNotification(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/preview",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailCampaignMessage performs GET /{version}/notifications/emails/campaigns/{campaignId}/messages/{id} (scope: project).
func (m *NotificationsModule) GetEmailCampaignMessage(ctx context.Context, campaignId string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"campaignId": campaignId,
		"id":         id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/emails/campaigns/{campaignId}/messages/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetEmailCampaignMessages performs GET /{version}/notifications/emails/campaigns/{campaignId}/messages (scope: project).
func (m *NotificationsModule) GetEmailCampaignMessages(ctx context.Context, campaignId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"campaignId": campaignId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/emails/campaigns/{campaignId}/messages",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisablePush performs GET /{version}/notifications/push/disable (scope: project).
func (m *NotificationsModule) DisablePush(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/disable",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnablePush performs GET /{version}/notifications/push/enable (scope: project).
func (m *NotificationsModule) EnablePush(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/enable",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ArchivePushTemplate performs PUT /{version}/notifications/push/templates/{Id}/archive (scope: project).
func (m *NotificationsModule) ArchivePushTemplate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/templates/{Id}/archive",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ClonePushTemplate performs POST /{version}/notifications/push/templates/{Id}/clone (scope: project).
func (m *NotificationsModule) ClonePushTemplate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/templates/{Id}/clone",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// CreatePushTemplate performs POST /{version}/notifications/push/templates (scope: project).
func (m *NotificationsModule) CreatePushTemplate(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/templates",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeletePushTemplate performs DELETE /{version}/notifications/push/templates/{Id} (scope: project).
func (m *NotificationsModule) DeletePushTemplate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/templates/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPushTemplate performs GET /{version}/notifications/push/templates/{id} (scope: project).
func (m *NotificationsModule) GetPushTemplate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/templates/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPushTemplates performs GET /{version}/notifications/push/templates (scope: project).
func (m *NotificationsModule) GetPushTemplates(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/templates",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPushMessageContentTokens performs GET /{version}/notifications/push/templates/{id}/tokens (scope: project).
func (m *NotificationsModule) GetPushMessageContentTokens(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/templates/{id}/tokens",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UnArchivePushTemplate performs PUT /{version}/notifications/push/templates/{Id}/unarchive (scope: project).
func (m *NotificationsModule) UnArchivePushTemplate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/templates/{Id}/unarchive",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdatePushTemplate performs PUT /{version}/notifications/push/templates (scope: project).
func (m *NotificationsModule) UpdatePushTemplate(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/templates",
		Method:     "PUT",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ConfirmPushIntegrationHumanDelivery performs POST /{version}/notifications/push/integrations/confirm-human-delivery (scope: project).
func (m *NotificationsModule) ConfirmPushIntegrationHumanDelivery(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/integrations/confirm-human-delivery",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeletePushIntegration performs DELETE /{version}/notifications/push/integrations/{Id} (scope: project).
func (m *NotificationsModule) DeletePushIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/integrations/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisablePushIntegration performs PUT /{version}/notifications/push/integrations/{Id}/disable (scope: project).
func (m *NotificationsModule) DisablePushIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/integrations/{Id}/disable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnablePushIntegration performs PUT /{version}/notifications/push/integrations/{Id}/enable (scope: project).
func (m *NotificationsModule) EnablePushIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/integrations/{Id}/enable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPushIntegration performs GET /{version}/notifications/push/integrations/{id} (scope: project).
func (m *NotificationsModule) GetPushIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/integrations/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPushIntegrations performs GET /{version}/notifications/push/integrations (scope: project).
func (m *NotificationsModule) GetPushIntegrations(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/integrations",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SavePushIntegration performs POST /{version}/notifications/push/integrations (scope: project).
func (m *NotificationsModule) SavePushIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/integrations",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SetPushIntegrationAsDefault performs PUT /{version}/notifications/push/integrations/{Id}/default (scope: project).
func (m *NotificationsModule) SetPushIntegrationAsDefault(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/integrations/{Id}/default",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// TestPushIntegration performs POST /{version}/notifications/push/integrations/test (scope: project).
func (m *NotificationsModule) TestPushIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/integrations/test",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RegisterCodeMashAppPushIntegration performs POST /{version}/notifications/push/integrations/app/request (scope: account).
func (m *NotificationsModule) RegisterCodeMashAppPushIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/integrations/app/request",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeAccount,
	}, out)
}

// RegisterDevice performs POST /{version}/notifications/push/devices (scope: project).
func (m *NotificationsModule) RegisterDevice(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/devices",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetAllContacts performs GET /{version}/notifications/contacts (scope: project).
func (m *NotificationsModule) GetAllContacts(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/contacts",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// CreateContact performs POST /{version}/notifications/contacts (scope: project).
func (m *NotificationsModule) CreateContact(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/contacts",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// MergeContacts performs POST /{version}/notifications/contacts/merge (scope: project).
func (m *NotificationsModule) MergeContacts(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/contacts/merge",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteContact performs DELETE /{version}/notifications/contacts/{contactId} (scope: project).
func (m *NotificationsModule) DeleteContact(ctx context.Context, contactId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"contactId": contactId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/contacts/{contactId}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetContact performs GET /{version}/notifications/contacts/{contactId} (scope: project).
func (m *NotificationsModule) GetContact(ctx context.Context, contactId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"contactId": contactId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/contacts/{contactId}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// AddContactIdentity performs POST /{version}/notifications/contacts/{contactId}/identities (scope: project).
func (m *NotificationsModule) AddContactIdentity(ctx context.Context, contactId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"contactId": contactId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/contacts/{contactId}/identities",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RemoveContactIdentity performs DELETE /{version}/notifications/contacts/{contactId}/identities/{identityId} (scope: project).
func (m *NotificationsModule) RemoveContactIdentity(ctx context.Context, contactId string, identityId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"contactId":  contactId,
		"identityId": identityId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/contacts/{contactId}/identities/{identityId}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// PromoteContactIdentity performs POST /{version}/notifications/contacts/{contactId}/identities/{identityId}/promote (scope: project).
func (m *NotificationsModule) PromoteContactIdentity(ctx context.Context, contactId string, identityId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"contactId":  contactId,
		"identityId": identityId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/contacts/{contactId}/identities/{identityId}/promote",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GrantContactConsent performs POST /{version}/notifications/contacts/{contactId}/marketing-state/{channel}/consent (scope: project).
func (m *NotificationsModule) GrantContactConsent(ctx context.Context, contactId string, channel string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"contactId": contactId,
		"channel":   channel,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/contacts/{contactId}/marketing-state/{channel}/consent",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UnsubscribeContact performs POST /{version}/notifications/contacts/{contactId}/marketing-state/{channel}/unsubscribe (scope: project).
func (m *NotificationsModule) UnsubscribeContact(ctx context.Context, contactId string, channel string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"contactId": contactId,
		"channel":   channel,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/contacts/{contactId}/marketing-state/{channel}/unsubscribe",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RazorSyntaxCheck performs POST /{version}/notifications/email/templates/razor-syntax-check (scope: project).
func (m *NotificationsModule) RazorSyntaxCheck(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/templates/razor-syntax-check",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveEmailValidationIntegration performs POST /{version}/notifications/email/validation/integrations (scope: project).
func (m *NotificationsModule) SaveEmailValidationIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/validation/integrations",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// TestEmailValidationIntegration performs POST /{version}/notifications/email/validation/integrations/test (scope: project).
func (m *NotificationsModule) TestEmailValidationIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/email/validation/integrations/test",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPushCampaigns performs GET /{version}/notifications/push/campaigns (scope: project).
func (m *NotificationsModule) GetPushCampaigns(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/campaigns",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// CreatePushCampaign performs POST /{version}/notifications/push/campaigns (scope: project).
func (m *NotificationsModule) CreatePushCampaign(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/campaigns",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeletePushCampaign performs DELETE /{version}/notifications/push/campaigns/{Id} (scope: project).
func (m *NotificationsModule) DeletePushCampaign(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/campaigns/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPushCampaignMessages performs GET /{version}/notifications/push/campaigns/{campaignId}/messages (scope: project).
func (m *NotificationsModule) GetPushCampaignMessages(ctx context.Context, campaignId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"campaignId": campaignId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/campaigns/{campaignId}/messages",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPushCampaignMessage performs GET /{version}/notifications/push/campaigns/{campaignId}/messages/{id} (scope: project).
func (m *NotificationsModule) GetPushCampaignMessage(ctx context.Context, campaignId string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"campaignId": campaignId,
		"id":         id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/campaigns/{campaignId}/messages/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPushCampaign performs GET /{version}/notifications/push/campaigns/{id} (scope: project).
func (m *NotificationsModule) GetPushCampaign(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/campaigns/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPushCampaignBatches performs GET /{version}/notifications/push/campaigns/{id}/batches (scope: project).
func (m *NotificationsModule) GetPushCampaignBatches(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/campaigns/{id}/batches",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPushCampaignBatchNotifications performs GET /{version}/notifications/push/campaigns/{id}/batches/{batchId} (scope: project).
func (m *NotificationsModule) GetPushCampaignBatchNotifications(ctx context.Context, id string, batchId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id":      id,
		"batchId": batchId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/campaigns/{id}/batches/{batchId}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPushCampaignBatchNotification performs GET /{version}/notifications/push/campaigns/{id}/batches/{batchId}/{notificationId} (scope: project).
func (m *NotificationsModule) GetPushCampaignBatchNotification(ctx context.Context, id string, batchId string, notificationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id":             id,
		"batchId":        batchId,
		"notificationId": notificationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/campaigns/{id}/batches/{batchId}/{notificationId}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPushCampaignStatistics performs GET /{version}/notifications/push/campaigns/{id}/stats (scope: project).
func (m *NotificationsModule) GetPushCampaignStatistics(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/campaigns/{id}/stats",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// CheckIntegrationAvailability performs POST /{version}/notifications/push/integrations/app/check (scope: project).
func (m *NotificationsModule) CheckIntegrationAvailability(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/integrations/app/check",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// TestCodeMashIosAppIntegration performs POST /{version}/notifications/push/integrations/test/codemash-app (scope: project).
func (m *NotificationsModule) TestCodeMashIosAppIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/integrations/test/codemash-app",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPushSettings performs GET /{version}/notifications/push/settings (scope: project).
func (m *NotificationsModule) GetPushSettings(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/push/settings",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSmsCampaigns performs GET /{version}/notifications/sms/campaigns (scope: project).
func (m *NotificationsModule) GetSmsCampaigns(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/campaigns",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// CreateSmsCampaign performs POST /{version}/notifications/sms/campaigns (scope: project).
func (m *NotificationsModule) CreateSmsCampaign(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/campaigns",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSmsCampaignMessages performs GET /{version}/notifications/sms/campaigns/{campaignId}/messages (scope: project).
func (m *NotificationsModule) GetSmsCampaignMessages(ctx context.Context, campaignId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"campaignId": campaignId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/campaigns/{campaignId}/messages",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSmsCampaignMessage performs GET /{version}/notifications/sms/campaigns/{campaignId}/messages/{id} (scope: project).
func (m *NotificationsModule) GetSmsCampaignMessage(ctx context.Context, campaignId string, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"campaignId": campaignId,
		"id":         id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/campaigns/{campaignId}/messages/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteSmsCampaign performs DELETE /{version}/notifications/sms/campaigns/{id} (scope: project).
func (m *NotificationsModule) DeleteSmsCampaign(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/campaigns/{id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSmsCampaign performs GET /{version}/notifications/sms/campaigns/{id} (scope: project).
func (m *NotificationsModule) GetSmsCampaign(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/campaigns/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSmsCampaignBatches performs GET /{version}/notifications/sms/campaigns/{id}/batches (scope: project).
func (m *NotificationsModule) GetSmsCampaignBatches(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/campaigns/{id}/batches",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSmsCampaignBatchNotifications performs GET /{version}/notifications/sms/campaigns/{id}/batches/{batchId} (scope: project).
func (m *NotificationsModule) GetSmsCampaignBatchNotifications(ctx context.Context, id string, batchId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id":      id,
		"batchId": batchId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/campaigns/{id}/batches/{batchId}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSmsCampaignBatchNotification performs GET /{version}/notifications/sms/campaigns/{id}/batches/{batchId}/{notificationId} (scope: project).
func (m *NotificationsModule) GetSmsCampaignBatchNotification(ctx context.Context, id string, batchId string, notificationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id":             id,
		"batchId":        batchId,
		"notificationId": notificationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/campaigns/{id}/batches/{batchId}/{notificationId}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSmsCampaignStatistics performs GET /{version}/notifications/sms/campaigns/{id}/stats (scope: project).
func (m *NotificationsModule) GetSmsCampaignStatistics(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/campaigns/{id}/stats",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisableSms performs GET /{version}/notifications/sms/disable (scope: project).
func (m *NotificationsModule) DisableSms(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/disable",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableSms performs GET /{version}/notifications/sms/enable (scope: project).
func (m *NotificationsModule) EnableSms(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/enable",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSmsIntegrations performs GET /{version}/notifications/sms/integrations (scope: project).
func (m *NotificationsModule) GetSmsIntegrations(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/integrations",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveSmsIntegration performs POST /{version}/notifications/sms/integrations (scope: project).
func (m *NotificationsModule) SaveSmsIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/integrations",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ConfirmSmsIntegrationHumanDelivery performs POST /{version}/notifications/sms/integrations/confirm-human-delivery (scope: project).
func (m *NotificationsModule) ConfirmSmsIntegrationHumanDelivery(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/integrations/confirm-human-delivery",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// TestSmsIntegration performs POST /{version}/notifications/sms/integrations/test (scope: project).
func (m *NotificationsModule) TestSmsIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/integrations/test",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteSmsIntegration performs DELETE /{version}/notifications/sms/integrations/{Id} (scope: project).
func (m *NotificationsModule) DeleteSmsIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/integrations/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SetSmsIntegrationAsDefault performs PUT /{version}/notifications/sms/integrations/{Id}/default (scope: project).
func (m *NotificationsModule) SetSmsIntegrationAsDefault(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/integrations/{Id}/default",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisableSmsIntegration performs PUT /{version}/notifications/sms/integrations/{Id}/disable (scope: project).
func (m *NotificationsModule) DisableSmsIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/integrations/{Id}/disable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableSmsIntegration performs PUT /{version}/notifications/sms/integrations/{Id}/enable (scope: project).
func (m *NotificationsModule) EnableSmsIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/integrations/{Id}/enable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSmsIntegration performs GET /{version}/notifications/sms/integrations/{id} (scope: project).
func (m *NotificationsModule) GetSmsIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/integrations/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// PreviewSmsNotification performs GET /{version}/notifications/sms/preview (scope: project).
func (m *NotificationsModule) PreviewSmsNotification(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/preview",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSmsSettings performs GET /{version}/notifications/sms/settings (scope: project).
func (m *NotificationsModule) GetSmsSettings(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/settings",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSmsTemplates performs GET /{version}/notifications/sms/templates (scope: project).
func (m *NotificationsModule) GetSmsTemplates(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/templates",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// CreateSmsTemplate performs POST /{version}/notifications/sms/templates (scope: project).
func (m *NotificationsModule) CreateSmsTemplate(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/templates",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateSmsTemplate performs PUT /{version}/notifications/sms/templates (scope: project).
func (m *NotificationsModule) UpdateSmsTemplate(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/templates",
		Method:     "PUT",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SmsRazorSyntaxCheck performs POST /{version}/notifications/sms/templates/razor-syntax-check (scope: project).
func (m *NotificationsModule) SmsRazorSyntaxCheck(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/templates/razor-syntax-check",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteSmsTemplate performs DELETE /{version}/notifications/sms/templates/{Id} (scope: project).
func (m *NotificationsModule) DeleteSmsTemplate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/templates/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ArchiveSmsTemplate performs PUT /{version}/notifications/sms/templates/{Id}/archive (scope: project).
func (m *NotificationsModule) ArchiveSmsTemplate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/templates/{Id}/archive",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// CloneSmsTemplate performs POST /{version}/notifications/sms/templates/{Id}/clone (scope: project).
func (m *NotificationsModule) CloneSmsTemplate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/templates/{Id}/clone",
		Method:     "POST",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UnArchiveSmsTemplate performs PUT /{version}/notifications/sms/templates/{Id}/unarchive (scope: project).
func (m *NotificationsModule) UnArchiveSmsTemplate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/templates/{Id}/unarchive",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSmsTemplate performs GET /{version}/notifications/sms/templates/{id} (scope: project).
func (m *NotificationsModule) GetSmsTemplate(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/templates/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSmsMessageContentTokens performs GET /{version}/notifications/sms/templates/{id}/tokens (scope: project).
func (m *NotificationsModule) GetSmsMessageContentTokens(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/notifications/sms/templates/{id}/tokens",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
