// Code generated by gen_modules.py. DO NOT EDIT.

package hub

import (
	"context"

	"github.com/norbix-code/sdk-go/norbix/internal/transport"
)

// PaymentsModule groups the payments endpoints on the HUB.
type PaymentsModule struct{ t *transport.Transport }

// DisablePayments performs GET /{version}/payments/disable (scope: project).
func (m *PaymentsModule) DisablePayments(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/payments/disable",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnablePayments performs GET /{version}/payments/enable (scope: project).
func (m *PaymentsModule) EnablePayments(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/payments/enable",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeletePaymentsTrigger performs DELETE /{version}/payments/triggers/{triggerId} (scope: project).
func (m *PaymentsModule) DeletePaymentsTrigger(ctx context.Context, triggerId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"triggerId": triggerId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/payments/triggers/{triggerId}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisablePaymentsTrigger performs PATCH /{version}/payments/triggers/{triggerId}/disable (scope: project).
func (m *PaymentsModule) DisablePaymentsTrigger(ctx context.Context, triggerId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"triggerId": triggerId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/payments/triggers/{triggerId}/disable",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnablePaymentsTrigger performs PATCH /{version}/payments/triggers/{triggerId}/enable (scope: project).
func (m *PaymentsModule) EnablePaymentsTrigger(ctx context.Context, triggerId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"triggerId": triggerId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/payments/triggers/{triggerId}/enable",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPaymentsTrigger performs GET /{version}/payments/triggers/{id} (scope: project).
func (m *PaymentsModule) GetPaymentsTrigger(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/payments/triggers/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPaymentsTriggers performs GET /{version}/payments/triggers (scope: project).
func (m *PaymentsModule) GetPaymentsTriggers(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/payments/triggers",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SavePaymentsTrigger performs POST /{version}/payments/triggers (scope: project).
func (m *PaymentsModule) SavePaymentsTrigger(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/payments/triggers",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// ConfirmPaymentsIntegrationHumanDelivery performs POST /{version}/payments/integrations/confirm-human-delivery (scope: project).
func (m *PaymentsModule) ConfirmPaymentsIntegrationHumanDelivery(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/payments/integrations/confirm-human-delivery",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeletePaymentsIntegration performs DELETE /{version}/payments/integrations/{Id} (scope: project).
func (m *PaymentsModule) DeletePaymentsIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/payments/integrations/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisablePaymentsIntegration performs PUT /{version}/payments/integrations/{Id}/disable (scope: project).
func (m *PaymentsModule) DisablePaymentsIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/payments/integrations/{Id}/disable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnablePaymentsIntegration performs PUT /{version}/payments/integrations/{Id}/enable (scope: project).
func (m *PaymentsModule) EnablePaymentsIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/payments/integrations/{Id}/enable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPaymentsIntegration performs GET /{version}/payments/integrations/{id} (scope: project).
func (m *PaymentsModule) GetPaymentsIntegration(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/payments/integrations/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetPaymentsIntegrations performs GET /{version}/payments/integrations (scope: project).
func (m *PaymentsModule) GetPaymentsIntegrations(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/payments/integrations",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SavePaymentsIntegration performs POST /{version}/payments/integrations (scope: project).
func (m *PaymentsModule) SavePaymentsIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/payments/integrations",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// TestPaymentsIntegration performs POST /{version}/payments/integrations/test (scope: project).
func (m *PaymentsModule) TestPaymentsIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/payments/integrations/test",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
