// Code generated by gen_modules.py. DO NOT EDIT.

package hub

import (
	"context"

	"github.com/norbix-code/sdk-go/v2/norbix/internal/transport"
)

// RegionsModule groups the regions endpoints on the HUB.
type RegionsModule struct{ t *transport.Transport }

// List performs GET /{version}/account/regions (scope: project).
func (m *RegionsModule) List(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/regions",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateProjectRegions performs PATCH /{version}/account/projects/{projectId}/settings/regions (scope: project).
func (m *RegionsModule) UpdateProjectRegions(ctx context.Context, projectId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"projectId": projectId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/account/projects/{projectId}/settings/regions",
		Method:     "PATCH",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
