// Code generated by gen_modules.py. DO NOT EDIT.

package hub

import (
	"context"

	"github.com/norbix-code/sdk-go/norbix/internal/transport"
)

// ResourcesModule groups the resources endpoints on the HUB.
type ResourcesModule struct{ t *transport.Transport }

// ResolveResources performs POST /{version}/resources/resolve (scope: project).
func (m *ResourcesModule) ResolveResources(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/resources/resolve",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
