// Code generated by gen_modules.py. DO NOT EDIT.

package hub

import (
	"context"

	"github.com/norbix-code/sdk-go/v2/norbix/internal/transport"
)

// SchedulerModule groups the scheduler endpoints on the HUB.
type SchedulerModule struct{ t *transport.Transport }

// DisableScheduler performs PUT /{version}/scheduler/disable (scope: project).
func (m *SchedulerModule) DisableScheduler(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/scheduler/disable",
		Method:     "PUT",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableScheduler performs PUT /{version}/scheduler/enable (scope: project).
func (m *SchedulerModule) EnableScheduler(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/scheduler/enable",
		Method:     "PUT",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DeleteSchedulerTask performs DELETE /{version}/scheduler/tasks/{Id} (scope: project).
func (m *SchedulerModule) DeleteSchedulerTask(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/scheduler/tasks/{Id}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisableSchedulerTask performs PUT /{version}/scheduler/tasks/{Id}/disable (scope: project).
func (m *SchedulerModule) DisableSchedulerTask(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/scheduler/tasks/{Id}/disable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableSchedulerTask performs PUT /{version}/scheduler/tasks/{Id}/enable (scope: project).
func (m *SchedulerModule) EnableSchedulerTask(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"Id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/scheduler/tasks/{Id}/enable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSchedulerTask performs GET /{version}/scheduler/tasks/{id} (scope: project).
func (m *SchedulerModule) GetSchedulerTask(ctx context.Context, id string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"id": id,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/scheduler/tasks/{id}",
		Method:     "GET",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// GetSchedulerTasks performs GET /{version}/scheduler/tasks (scope: project).
func (m *SchedulerModule) GetSchedulerTasks(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/scheduler/tasks",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveSchedulerTask performs POST /{version}/scheduler/tasks (scope: project).
//
// req carries initiatorUserId, name, cron (5 fields, UTC), isEnabled,
// stopOnError, an optional taskId (update) and task. "task" may be a
// dtos.EmailCampaignSchedulerTaskRequest (type "EmailCampaign", the only task
// type the gateway runs today) or the same shape as a map. See
// docs/hub/scheduler.md for a full example.
func (m *SchedulerModule) SaveSchedulerTask(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/scheduler/tasks",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
