// Code generated by gen_modules.py. DO NOT EDIT.

package hub

import (
	"context"

	"github.com/norbix-code/sdk-go/norbix/internal/transport"
)

// WebhooksModule groups the webhooks endpoints on the HUB.
type WebhooksModule struct{ t *transport.Transport }

// GetWebhookIntegration performs GET /{version}/webhooks/integration (scope: project).
func (m *WebhooksModule) GetWebhookIntegration(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/webhooks/integration",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RevealWebhookIntegrationSecret performs GET /{version}/webhooks/integration/secret (scope: project).
func (m *WebhooksModule) RevealWebhookIntegrationSecret(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/webhooks/integration/secret",
		Method:     "GET",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RotateWebhookIntegrationSecret performs POST /{version}/webhooks/integration/secret/rotate (scope: project).
func (m *WebhooksModule) RotateWebhookIntegrationSecret(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/webhooks/integration/secret/rotate",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// UpdateWebhookIntegrationExtraHeaders performs PUT /{version}/webhooks/integration/extra-headers (scope: project).
func (m *WebhooksModule) UpdateWebhookIntegrationExtraHeaders(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/webhooks/integration/extra-headers",
		Method:     "PUT",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// DisableWebhookDestination performs PUT /{version}/webhooks/destinations/{DestinationId}/disable (scope: project).
func (m *WebhooksModule) DisableWebhookDestination(ctx context.Context, destinationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"DestinationId": destinationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/webhooks/destinations/{DestinationId}/disable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// EnableWebhookDestination performs PUT /{version}/webhooks/destinations/{DestinationId}/enable (scope: project).
func (m *WebhooksModule) EnableWebhookDestination(ctx context.Context, destinationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"DestinationId": destinationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/webhooks/destinations/{DestinationId}/enable",
		Method:     "PUT",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// RemoveWebhookDestination performs DELETE /{version}/webhooks/destinations/{DestinationId} (scope: project).
func (m *WebhooksModule) RemoveWebhookDestination(ctx context.Context, destinationId string, req map[string]any, out any) error {
	pathParams := map[string]string{
		"DestinationId": destinationId,
	}
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/webhooks/destinations/{DestinationId}",
		Method:     "DELETE",
		PathParams: pathParams,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}

// SaveWebhookDestination performs POST /{version}/webhooks/destinations (scope: project).
func (m *WebhooksModule) SaveWebhookDestination(ctx context.Context, req map[string]any, out any) error {
	return m.t.Send(ctx, transport.Request{
		Target:     transport.TargetHub,
		Path:       "/{version}/webhooks/destinations",
		Method:     "POST",
		PathParams: nil,
		Body:       req,
		Scope:      transport.ScopeProject,
	}, out)
}
